#ifndef SUSAMUNE_MEM2_MAP_H
#define SUSAMUNE_MEM2_MAP_H

// Shared Wii MEM2 layout for the PPC loader/mod and the ARM Nintendont kernel.
// ARM uses physical 0x1xxxxxxx addresses; PPC cached aliases add 0x80000000.
// Keep this file C-compatible: it is included by all three build toolchains.

// ISO images and real discs are mutually exclusive, so both readers share the
// first 3 MiB. RealDI divides it into front/drive/tail-cache subranges.
#define NIN_MEM2_DISC_CACHE_PHYS_BASE         0x11000000u
#define NIN_MEM2_DISC_CACHE_PPC_BASE          0x91000000u
#define NIN_MEM2_DISC_CACHE_SIZE              0x00300000u

// Nintendont buffers relocated below the savestate window.
#define NIN_MEM2_SEGABOOT_PHYS_BASE          0x11300000u
#define NIN_MEM2_SEGABOOT_PPC_BASE           0x91300000u
#define NIN_MEM2_SEGABOOT_SIZE               0x00100000u

#define NIN_MEM2_DIMM_PHYS_BASE              0x11400000u
#define NIN_MEM2_DIMM_PPC_BASE               0x91400000u
#define NIN_MEM2_DIMM_SIZE                   0x00300000u

/* Loader-only overlay. A normal GameCube IPL and Triforce are exclusive. */
#define SUSAMUNE_LAUNCHER_GCN_IPL_PPC_BASE   NIN_MEM2_DIMM_PPC_BASE
#define SUSAMUNE_LAUNCHER_GCN_IPL_SIZE       0x00200000u

#define NIN_MEM2_DI_SCRATCH_PHYS_BASE        0x11700000u
#define NIN_MEM2_DI_SCRATCH_PPC_BASE         0x91700000u
#define NIN_MEM2_DI_SCRATCH_SIZE             0x00080000u

// Used only by the PPC loader before control passes to the game/kernel.
#define NIN_MEM2_LOADER_DISC_PHYS_BASE       0x11780000u
#define NIN_MEM2_LOADER_DISC_PPC_BASE        0x91780000u
#define NIN_MEM2_LOADER_DISC_SIZE            0x00180000u

// Runtime ghost slots reuse the loader's disc buffer only after it has handed
// control to the game. The third slot is the bounded ARM/PPC file mailbox.
#define SUSAMUNE_GHOST_SLOT_SIZE                0x00080000u
#define SUSAMUNE_CONSOLE_GHOST_RECORD_PHYS_BASE 0x11780000u
#define SUSAMUNE_CONSOLE_GHOST_RECORD_PPC_BASE  0x91780000u
#define SUSAMUNE_CONSOLE_GHOST_PLAY_PHYS_BASE   0x11800000u
#define SUSAMUNE_CONSOLE_GHOST_PLAY_PPC_BASE    0x91800000u
#define SUSAMUNE_CONSOLE_GHOST_TRANSFER_PHYS_BASE 0x11880000u
#define SUSAMUNE_CONSOLE_GHOST_TRANSFER_PPC_BASE 0x91880000u

// patch.bin / patch.txt handoff: the loader writes through the cached PPC
// alias and the ARM kernel consumes the same bytes through the physical alias.
#define NIN_MEM2_FILE_PATCH_PHYS_BASE        0x11900000u
#define NIN_MEM2_FILE_PATCH_PPC_BASE         0x91900000u
#define NIN_MEM2_FILE_PATCH_SIZE             0x0057F000u

// mod_<region>.bin staging (struct SusamuneModHeader, mod_bin.h). The PPC
// loader reads the file for the detected disc here before booting the kernel;
// PatchSusamune() copies the code out into MEM1. PatchGame can consume this
// staging prefix again after an in-session reset, so it remains immutable.
//
// It shares the file-patch buffer's lifetime -- both are loader-to-kernel
// handoffs consumed at PatchGame time -- so it is carved off that buffer's tail
// rather than given memory of its own: 516 KiB out of six MiB, and the game
// never ships a patch.bin anyway. Deliberately NOT taken out of the snapshot
// window, whose payload can legitimately grow to fill its reservation.
#define SUSAMUNE_MEM2_MODBIN_PHYS_BASE       0x11E7F000u
#define SUSAMUNE_MEM2_MODBIN_PPC_BASE        0x91E7F000u
#define SUSAMUNE_MEM2_MODBIN_SIZE            0x00081000u

// PatchGame can consume the staged mod again after an in-session reset. The
// file may use the complete prefix before the immutable model-asset vault.
#define SUSAMUNE_MOD_STAGED_FILE_MAX_SIZE         0x0005F000u

// PatchSusamune consumes the complete mod staging file before the kernel
// publishes immutable retail model assets into its now-dead tail.
#define SUSAMUNE_GHOST_ASSET_VAULT_OFFSET         0x0005F000u
#define SUSAMUNE_GHOST_SHADOW_MASTER_OFFSET       0x00000000u
#define SUSAMUNE_GHOST_SHADOW_MASTER_SIZE         0x00010000u
#define SUSAMUNE_GHOST_PIANTA_MASTER_OFFSET       0x00010000u
#define SUSAMUNE_GHOST_PIANTA_MASTER_SIZE         0x00012000u
#define SUSAMUNE_GHOST_ASSET_VAULT_SIZE           0x00022000u
#define SUSAMUNE_GHOST_ASSET_VAULT_PHYS_BASE \
    (SUSAMUNE_MEM2_MODBIN_PHYS_BASE + SUSAMUNE_GHOST_ASSET_VAULT_OFFSET)
#define SUSAMUNE_GHOST_ASSET_VAULT_PPC_BASE \
    (SUSAMUNE_MEM2_MODBIN_PPC_BASE + SUSAMUNE_GHOST_ASSET_VAULT_OFFSET)

// Dedicated Susamune snapshot window. No Nintendont buffer may overlap this
// range. Its exclusive end is the settings block below.
#define SUSAMUNE_MEM2_SNAPSHOT_PHYS_BASE     0x11F00000u
#define SUSAMUNE_MEM2_SNAPSHOT_PPC_BASE      0x91F00000u
#define SUSAMUNE_MEM2_SNAPSHOT_SIZE          0x00FF0000u

/* Loader-only overlay. Music stops before the game can create a snapshot. */
#define SUSAMUNE_LAUNCHER_MUSIC_PPC_BASE     SUSAMUNE_MEM2_SNAPSHOT_PPC_BASE
#define SUSAMUNE_LAUNCHER_MUSIC_SIZE         0x00400000u

// Dolphin exposes a separate 16 MiB aperture for the snapshot. Keep its final
// 64 KiB outside the snapshot payload for live emulator-only state; unlike the
// Wii addresses below, nothing on the ARM side consumes these bytes.
#define SUSAMUNE_DOLPHIN_SNAPSHOT_PPC_BASE   0x70000000u
#define SUSAMUNE_DOLPHIN_RUNTIME_PPC_BASE    0x70FF0000u
#define SUSAMUNE_DOLPHIN_RUNTIME_SIZE        0x00010000u
#define SUSAMUNE_DOLPHIN_PERSIST_PPC_BASE    0x70FF0000u
#define SUSAMUNE_DOLPHIN_PERSIST_SIZE        0x00001800u
#define SUSAMUNE_DOLPHIN_RECORDS_PPC_BASE    0x70FF1800u
#define SUSAMUNE_DOLPHIN_METADATA_PPC_BASE   0x70FF2000u
#define SUSAMUNE_DOLPHIN_CREATION_PPC_BASE   0x70FF2800u
#define SUSAMUNE_DOLPHIN_REGIONAL_PPC_BASE   0x70FF2D00u
#define SUSAMUNE_DOLPHIN_MENU_PPC_BASE       0x70FF2F00u
#define SUSAMUNE_DOLPHIN_CONFIG_PPC_BASE     0x70FF3300u
#define SUSAMUNE_DOLPHIN_FEATURE_PPC_BASE    0x70FF3500u
#define SUSAMUNE_DOLPHIN_ILING_PPC_BASE      0x70FF3600u
#define SUSAMUNE_DOLPHIN_STAGE_LOADER_PPC_BASE 0x70FF3700u
#define SUSAMUNE_DOLPHIN_CRASH_PPC_BASE      0x70FF3800u
#define SUSAMUNE_DOLPHIN_STAGE_LOADER_QUEUE_PPC_BASE 0x70FF4800u
#define SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE    0x70FFF800u
#define SUSAMUNE_DOLPHIN_PB_LIVE_SIZE        0x00000800u

// Keep Dolphin's ghost slots in the same three-slot shape as console.
#define SUSAMUNE_DOLPHIN_GHOST_RECORD_PPC_BASE  0x71000000u
#define SUSAMUNE_DOLPHIN_GHOST_PLAY_PPC_BASE    0x71080000u
#define SUSAMUNE_DOLPHIN_GHOST_TRANSFER_PPC_BASE 0x71100000u

// J3D allocations for the visual-only ghost live in the unused gap between
// the maximum 15-minute sample payload and the V2 segment table. The fixed
// heap has 0x15ed0 usable bytes; Shadow Mario's checked bound is 0x12000.
#define SUSAMUNE_GHOST_MODEL_HEAP_OFFSET          0x000695E0u
#define SUSAMUNE_GHOST_MODEL_HEAP_SIZE            0x00016000u
#define SUSAMUNE_GHOST_CATALOG_CACHE_OFFSET        0x000795E0u
#define SUSAMUNE_GHOST_CATALOG_CACHE_SIZE          0x00001E00u
#define SUSAMUNE_GHOST_SEGMENT_TABLE_OFFSET       0x0007F800u
#define SUSAMUNE_GHOST_TRANSFER_MAILBOX_HEADER_SIZE 0x00000100u
#define SUSAMUNE_GHOST_SECONDARY_HEAP_OFFSET      0x0006A000u
#define SUSAMUNE_GHOST_SECONDARY_HEAP_SIZE        0x00016000u

// Settings/PB handoff block (struct SusamuneCfg, susamune_cfg.h). The ARM
// kernel fills it before boot and services the mod's independent ini and PB
// save doorbells. Carved off the top of the snapshot window rather than from
// Nintendont's buffers, since the snapshot's 16 MiB reservation is far larger
// than its use. Deliberately outside the snapshot payload so a savestate load
// does not rewind persistent data.
#define SUSAMUNE_MEM2_CFG_PHYS_BASE          0x12EF0000u
#define SUSAMUNE_MEM2_CFG_PPC_BASE           0x92EF0000u
#define SUSAMUNE_MEM2_CFG_SIZE               0x00010000u

// Runtime state lives after the progress mailbox and before the live PB
// mirror. Only the crash mailbox is shared back to the ARM kernel.
#define SUSAMUNE_CONSOLE_RECORDS_PPC_BASE    0x92EF2400u
#define SUSAMUNE_CONSOLE_METADATA_PPC_BASE   0x92EF2C00u
#define SUSAMUNE_CONSOLE_CREATION_PPC_BASE   0x92EF3400u
#define SUSAMUNE_CONSOLE_REGIONAL_PPC_BASE   0x92EF3900u
#define SUSAMUNE_CONSOLE_MENU_PPC_BASE       0x92EF3B00u
#define SUSAMUNE_CONSOLE_CONFIG_PPC_BASE     0x92EF3F00u
#define SUSAMUNE_CONSOLE_FEATURE_PPC_BASE    0x92EF4100u
#define SUSAMUNE_CONSOLE_ILING_PPC_BASE      0x92EF4200u
#define SUSAMUNE_CONSOLE_STAGE_LOADER_PPC_BASE 0x92EF4300u
#define SUSAMUNE_CONSOLE_CRASH_PHYS_BASE     0x12EF4400u
#define SUSAMUNE_CONSOLE_CRASH_PPC_BASE      0x92EF4400u
#define SUSAMUNE_CONSOLE_STAGE_LOADER_QUEUE_PPC_BASE 0x92EF5400u

#define SUSAMUNE_RECORDS_RUNTIME_SIZE         0x00000800u
#define SUSAMUNE_METADATA_RUNTIME_SIZE        0x00000800u
#define SUSAMUNE_CREATION_RUNTIME_SIZE        0x00000500u
#define SUSAMUNE_REGIONAL_RUNTIME_SIZE        0x00000200u
#define SUSAMUNE_MENU_RUNTIME_SIZE            0x00000400u
#define SUSAMUNE_CONFIG_RUNTIME_SIZE          0x00000200u
#define SUSAMUNE_FEATURE_RUNTIME_SIZE         0x00000100u
#define SUSAMUNE_ILING_RUNTIME_SIZE           0x00000100u
#define SUSAMUNE_STAGE_LOADER_RUNTIME_SIZE    0x00000100u
#define SUSAMUNE_MEM2_CRASH_SIZE              0x00001000u
#define SUSAMUNE_STAGE_LOADER_QUEUE_SIZE       0x00000100u
#define SUSAMUNE_STAGE_TARGETS_CFG_SIZE         0x00000240u
#define SUSAMUNE_STAGE_TARGETS_LIVE_SIZE        0x00000200u
#define SUSAMUNE_MENU_TEXT_SIZE                 0x00000200u

// Stage Loader targets occupy the low end of the otherwise-unused gap before
// the split-statistics mailbox. Derive both ends so schema growth cannot
// overlap them.
#define SUSAMUNE_CONSOLE_STAGE_TARGETS_PPC_BASE \
    (SUSAMUNE_CONSOLE_STAGE_LOADER_QUEUE_PPC_BASE + \
     SUSAMUNE_STAGE_LOADER_QUEUE_SIZE)
#define SUSAMUNE_CONSOLE_STAGE_TARGETS_PHYS_BASE \
    (SUSAMUNE_CONSOLE_STAGE_TARGETS_PPC_BASE - 0x80000000u)
#define SUSAMUNE_DOLPHIN_STAGE_TARGETS_PPC_BASE \
    (SUSAMUNE_DOLPHIN_STAGE_LOADER_QUEUE_PPC_BASE + \
     SUSAMUNE_STAGE_LOADER_QUEUE_SIZE)
#define SUSAMUNE_CONSOLE_MENU_TEXT_PPC_BASE \
    (SUSAMUNE_CONSOLE_STAGE_TARGETS_PPC_BASE + \
     SUSAMUNE_STAGE_TARGETS_CFG_SIZE + SUSAMUNE_STAGE_TARGETS_LIVE_SIZE)
#define SUSAMUNE_DOLPHIN_MENU_TEXT_PPC_BASE \
    (SUSAMUNE_DOLPHIN_STAGE_TARGETS_PPC_BASE + \
     SUSAMUNE_STAGE_TARGETS_CFG_SIZE + SUSAMUNE_STAGE_TARGETS_LIVE_SIZE)

#define SUSAMUNE_CONFIG_SETTINGS_OFFSET       0x00000000u
#define SUSAMUNE_CONFIG_SETTINGS_SIZE         0x00000084u
#define SUSAMUNE_CONFIG_BINDS_OFFSET          0x00000084u
#define SUSAMUNE_CONFIG_BINDS_SIZE            0x0000003Cu
#define SUSAMUNE_CONFIG_INPUT_OFFSET          0x000000C0u
#define SUSAMUNE_CONFIG_INPUT_SIZE            0x000000A0u
#define SUSAMUNE_CONFIG_QFT_OFFSET            0x00000160u
#define SUSAMUNE_CONFIG_QFT_SIZE              0x00000080u
#define SUSAMUNE_CONFIG_ATTEMPTS_OFFSET       0x000001E0u
#define SUSAMUNE_CONFIG_ATTEMPTS_SIZE         0x00000020u

#if IS_EMULATOR
#define SUSAMUNE_MEM2_RECORDS_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_RECORDS_PPC_BASE
#define SUSAMUNE_MEM2_METADATA_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_METADATA_PPC_BASE
#define SUSAMUNE_MEM2_CREATION_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_CREATION_PPC_BASE
#define SUSAMUNE_MEM2_REGIONAL_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_REGIONAL_PPC_BASE
#define SUSAMUNE_MEM2_MENU_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_MENU_PPC_BASE
#define SUSAMUNE_MEM2_CONFIG_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_CONFIG_PPC_BASE
#define SUSAMUNE_MEM2_FEATURE_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_FEATURE_PPC_BASE
#define SUSAMUNE_MEM2_ILING_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_ILING_PPC_BASE
#define SUSAMUNE_MEM2_STAGE_LOADER_RUNTIME_PPC_BASE \
    SUSAMUNE_DOLPHIN_STAGE_LOADER_PPC_BASE
#define SUSAMUNE_MEM2_CRASH_PPC_BASE SUSAMUNE_DOLPHIN_CRASH_PPC_BASE
#define SUSAMUNE_MEM2_CRASH_PHYS_BASE \
    (SUSAMUNE_DOLPHIN_CRASH_PPC_BASE - 0x60000000u)
#define SUSAMUNE_MEM2_STAGE_LOADER_QUEUE_PPC_BASE \
    SUSAMUNE_DOLPHIN_STAGE_LOADER_QUEUE_PPC_BASE
#define SUSAMUNE_MEM2_STAGE_TARGETS_PPC_BASE \
    SUSAMUNE_DOLPHIN_STAGE_TARGETS_PPC_BASE
#define SUSAMUNE_MEM2_MENU_TEXT_PPC_BASE \
    SUSAMUNE_DOLPHIN_MENU_TEXT_PPC_BASE
#define SUSAMUNE_GHOST_RECORD_PPC_BASE SUSAMUNE_DOLPHIN_GHOST_RECORD_PPC_BASE
#define SUSAMUNE_GHOST_PLAY_PPC_BASE SUSAMUNE_DOLPHIN_GHOST_PLAY_PPC_BASE
#define SUSAMUNE_GHOST_TRANSFER_PPC_BASE SUSAMUNE_DOLPHIN_GHOST_TRANSFER_PPC_BASE
#else
#define SUSAMUNE_MEM2_RECORDS_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_RECORDS_PPC_BASE
#define SUSAMUNE_MEM2_METADATA_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_METADATA_PPC_BASE
#define SUSAMUNE_MEM2_CREATION_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_CREATION_PPC_BASE
#define SUSAMUNE_MEM2_REGIONAL_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_REGIONAL_PPC_BASE
#define SUSAMUNE_MEM2_MENU_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_MENU_PPC_BASE
#define SUSAMUNE_MEM2_CONFIG_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_CONFIG_PPC_BASE
#define SUSAMUNE_MEM2_FEATURE_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_FEATURE_PPC_BASE
#define SUSAMUNE_MEM2_ILING_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_ILING_PPC_BASE
#define SUSAMUNE_MEM2_STAGE_LOADER_RUNTIME_PPC_BASE \
    SUSAMUNE_CONSOLE_STAGE_LOADER_PPC_BASE
#define SUSAMUNE_MEM2_CRASH_PPC_BASE SUSAMUNE_CONSOLE_CRASH_PPC_BASE
#define SUSAMUNE_MEM2_CRASH_PHYS_BASE SUSAMUNE_CONSOLE_CRASH_PHYS_BASE
#define SUSAMUNE_MEM2_STAGE_LOADER_QUEUE_PPC_BASE \
    SUSAMUNE_CONSOLE_STAGE_LOADER_QUEUE_PPC_BASE
#define SUSAMUNE_MEM2_STAGE_TARGETS_PPC_BASE \
    SUSAMUNE_CONSOLE_STAGE_TARGETS_PPC_BASE
#define SUSAMUNE_MEM2_MENU_TEXT_PPC_BASE \
    SUSAMUNE_CONSOLE_MENU_TEXT_PPC_BASE
#define SUSAMUNE_GHOST_RECORD_PPC_BASE SUSAMUNE_CONSOLE_GHOST_RECORD_PPC_BASE
#define SUSAMUNE_GHOST_PLAY_PPC_BASE SUSAMUNE_CONSOLE_GHOST_PLAY_PPC_BASE
#define SUSAMUNE_GHOST_TRANSFER_PPC_BASE SUSAMUNE_CONSOLE_GHOST_TRANSFER_PPC_BASE
#endif

#define SUSAMUNE_GHOST_MODEL_HEAP_PPC_BASE \
    (SUSAMUNE_GHOST_PLAY_PPC_BASE + SUSAMUNE_GHOST_MODEL_HEAP_OFFSET)
#define SUSAMUNE_GHOST_CATALOG_CACHE_PPC_BASE \
    (SUSAMUNE_GHOST_RECORD_PPC_BASE + SUSAMUNE_GHOST_CATALOG_CACHE_OFFSET)
#define SUSAMUNE_GHOST_SECONDARY_HEAP_PPC_BASE \
    (SUSAMUNE_GHOST_TRANSFER_PPC_BASE + \
     SUSAMUNE_GHOST_SECONDARY_HEAP_OFFSET)
#if SUSAMUNE_GHOST_MODEL_HEAP_OFFSET + SUSAMUNE_GHOST_MODEL_HEAP_SIZE > SUSAMUNE_GHOST_SEGMENT_TABLE_OFFSET
#error "ghost model heap overlaps the playback segment table"
#endif
#if SUSAMUNE_GHOST_CATALOG_CACHE_OFFSET + SUSAMUNE_GHOST_CATALOG_CACHE_SIZE > SUSAMUNE_GHOST_SEGMENT_TABLE_OFFSET
#error "ghost catalog cache overlaps the recording segment table"
#endif
#if (SUSAMUNE_GHOST_CATALOG_CACHE_OFFSET & 31u) != 0 || (SUSAMUNE_GHOST_CATALOG_CACHE_SIZE & 31u) != 0
#error "ghost catalog cache must be cache-line aligned"
#endif
#if SUSAMUNE_GHOST_SECONDARY_HEAP_OFFSET + SUSAMUNE_GHOST_SECONDARY_HEAP_SIZE != SUSAMUNE_GHOST_SLOT_SIZE
#error "secondary ghost model heap must exactly consume the transfer tail"
#endif
#if (SUSAMUNE_GHOST_SECONDARY_HEAP_OFFSET & 31u) != 0 || (SUSAMUNE_GHOST_SECONDARY_HEAP_SIZE & 31u) != 0
#error "ghost transfer/model boundaries must be cache-line aligned"
#endif
#if SUSAMUNE_GHOST_ASSET_VAULT_OFFSET + SUSAMUNE_GHOST_ASSET_VAULT_SIZE != SUSAMUNE_MEM2_MODBIN_SIZE || SUSAMUNE_GHOST_SHADOW_MASTER_OFFSET + SUSAMUNE_GHOST_SHADOW_MASTER_SIZE != SUSAMUNE_GHOST_PIANTA_MASTER_OFFSET || SUSAMUNE_GHOST_PIANTA_MASTER_OFFSET + SUSAMUNE_GHOST_PIANTA_MASTER_SIZE != SUSAMUNE_GHOST_ASSET_VAULT_SIZE
#error "ghost model asset vault must exactly consume the mod staging tail"
#endif
#if SUSAMUNE_MOD_STAGED_FILE_MAX_SIZE != SUSAMUNE_GHOST_ASSET_VAULT_OFFSET
#error "staged mod file must end at the immutable asset vault"
#endif

#if SUSAMUNE_CONFIG_SETTINGS_OFFSET + SUSAMUNE_CONFIG_SETTINGS_SIZE > SUSAMUNE_CONFIG_BINDS_OFFSET || SUSAMUNE_CONFIG_BINDS_OFFSET + SUSAMUNE_CONFIG_BINDS_SIZE > SUSAMUNE_CONFIG_INPUT_OFFSET || SUSAMUNE_CONFIG_INPUT_OFFSET + SUSAMUNE_CONFIG_INPUT_SIZE > SUSAMUNE_CONFIG_QFT_OFFSET || SUSAMUNE_CONFIG_QFT_OFFSET + SUSAMUNE_CONFIG_QFT_SIZE > SUSAMUNE_CONFIG_ATTEMPTS_OFFSET || SUSAMUNE_CONFIG_ATTEMPTS_OFFSET + SUSAMUNE_CONFIG_ATTEMPTS_SIZE > SUSAMUNE_CONFIG_RUNTIME_SIZE
#error "Susamune configuration runtime slots overlap"
#endif

// PPC-only live PB profiles. The ARM doorbell payload remains immutable while
// a save is in flight; later PB changes queue here for the next write.
#define SUSAMUNE_MEM2_PB_LIVE_PPC_BASE       0x92EFF800u
#define SUSAMUNE_MEM2_PB_LIVE_SIZE           0x00000800u

#define SUSAMUNE_MEM2_STAGE_TARGETS_LIVE_PPC_BASE \
    (SUSAMUNE_MEM2_STAGE_TARGETS_PPC_BASE + SUSAMUNE_STAGE_TARGETS_CFG_SIZE)

#define NIN_MEM2_KERNEL_PHYS_BASE            0x12F00000u
#define NIN_MEM2_KERNEL_PPC_BASE             0x92F00000u
// The loadable code/data image stops where kernel.ld starts ARM stacks.
#define NIN_MEM2_KERNEL_IMAGE_SIZE           0x000E0000u

// Compile-time adjacency checks. Besides documenting the intended ownership,
// these prevent a future size/address edit from silently entering the snapshot.
#if NIN_MEM2_DISC_CACHE_PHYS_BASE + NIN_MEM2_DISC_CACHE_SIZE != NIN_MEM2_SEGABOOT_PHYS_BASE
#error "MEM2 map gap/overlap between disc cache and SegaBoot"
#endif
#if NIN_MEM2_SEGABOOT_PHYS_BASE + NIN_MEM2_SEGABOOT_SIZE != NIN_MEM2_DIMM_PHYS_BASE
#error "MEM2 map gap/overlap between SegaBoot and DIMM buffers"
#endif
#if NIN_MEM2_DIMM_PHYS_BASE + NIN_MEM2_DIMM_SIZE != NIN_MEM2_DI_SCRATCH_PHYS_BASE
#error "MEM2 map gap/overlap between DIMM and DI scratch buffers"
#endif
#if NIN_MEM2_DI_SCRATCH_PPC_BASE + NIN_MEM2_DI_SCRATCH_SIZE != NIN_MEM2_LOADER_DISC_PPC_BASE
#error "MEM2 map gap/overlap before the loader disc buffer"
#endif
#if NIN_MEM2_LOADER_DISC_PPC_BASE + NIN_MEM2_LOADER_DISC_SIZE != NIN_MEM2_FILE_PATCH_PPC_BASE
#error "MEM2 map gap/overlap before the file-patch buffer"
#endif
#if SUSAMUNE_CONSOLE_GHOST_RECORD_PPC_BASE != NIN_MEM2_LOADER_DISC_PPC_BASE || SUSAMUNE_CONSOLE_GHOST_RECORD_PPC_BASE + SUSAMUNE_GHOST_SLOT_SIZE != SUSAMUNE_CONSOLE_GHOST_PLAY_PPC_BASE || SUSAMUNE_CONSOLE_GHOST_PLAY_PPC_BASE + SUSAMUNE_GHOST_SLOT_SIZE != SUSAMUNE_CONSOLE_GHOST_TRANSFER_PPC_BASE || SUSAMUNE_CONSOLE_GHOST_TRANSFER_PPC_BASE + SUSAMUNE_GHOST_SLOT_SIZE != NIN_MEM2_FILE_PATCH_PPC_BASE
#error "console ghost slots must exactly tile the loader disc buffer"
#endif
#if NIN_MEM2_FILE_PATCH_PHYS_BASE + NIN_MEM2_FILE_PATCH_SIZE != SUSAMUNE_MEM2_MODBIN_PHYS_BASE
#error "MEM2 file-patch buffer must end at the mod-blob staging area"
#endif
#if SUSAMUNE_MEM2_MODBIN_PHYS_BASE + SUSAMUNE_MEM2_MODBIN_SIZE != SUSAMUNE_MEM2_SNAPSHOT_PHYS_BASE
#error "MEM2 mod-blob staging area must end at the snapshot window"
#endif
#if SUSAMUNE_MEM2_SNAPSHOT_PHYS_BASE + SUSAMUNE_MEM2_SNAPSHOT_SIZE != SUSAMUNE_MEM2_CFG_PHYS_BASE
#error "MEM2 snapshot window must end at the settings block"
#endif
#if SUSAMUNE_LAUNCHER_MUSIC_PPC_BASE < SUSAMUNE_MEM2_SNAPSHOT_PPC_BASE || \
    SUSAMUNE_LAUNCHER_MUSIC_PPC_BASE + SUSAMUNE_LAUNCHER_MUSIC_SIZE > \
        SUSAMUNE_MEM2_SNAPSHOT_PPC_BASE + SUSAMUNE_MEM2_SNAPSHOT_SIZE || \
    (SUSAMUNE_LAUNCHER_MUSIC_PPC_BASE & 31u) != 0 || \
    (SUSAMUNE_LAUNCHER_MUSIC_SIZE & 31u) != 0
#error "Launcher music overlay must fit and align inside the snapshot window"
#endif
#if SUSAMUNE_LAUNCHER_GCN_IPL_PPC_BASE < NIN_MEM2_DIMM_PPC_BASE || \
    SUSAMUNE_LAUNCHER_GCN_IPL_PPC_BASE + SUSAMUNE_LAUNCHER_GCN_IPL_SIZE > \
        NIN_MEM2_DIMM_PPC_BASE + NIN_MEM2_DIMM_SIZE || \
    (SUSAMUNE_LAUNCHER_GCN_IPL_PPC_BASE & 31u) != 0 || \
    (SUSAMUNE_LAUNCHER_GCN_IPL_SIZE & 31u) != 0
#error "Launcher GameCube IPL overlay must fit and align inside DIMM memory"
#endif
#if SUSAMUNE_MEM2_CFG_PHYS_BASE + SUSAMUNE_MEM2_CFG_SIZE != NIN_MEM2_KERNEL_PHYS_BASE
#error "MEM2 settings block must end at the Nintendont kernel"
#endif
#if SUSAMUNE_MEM2_PB_LIVE_PPC_BASE + SUSAMUNE_MEM2_PB_LIVE_SIZE != NIN_MEM2_KERNEL_PPC_BASE
#error "MEM2 live PB mirror must end at the Nintendont kernel"
#endif
#if SUSAMUNE_DOLPHIN_SNAPSHOT_PPC_BASE + SUSAMUNE_MEM2_SNAPSHOT_SIZE != SUSAMUNE_DOLPHIN_RUNTIME_PPC_BASE
#error "Dolphin runtime state must follow the snapshot window"
#endif
#if SUSAMUNE_DOLPHIN_RUNTIME_PPC_BASE + SUSAMUNE_DOLPHIN_RUNTIME_SIZE != 0x71000000u
#error "Dolphin runtime state must stay inside its 16 MiB aperture"
#endif
#if SUSAMUNE_DOLPHIN_GHOST_RECORD_PPC_BASE != 0x71000000u || SUSAMUNE_DOLPHIN_GHOST_RECORD_PPC_BASE + SUSAMUNE_GHOST_SLOT_SIZE != SUSAMUNE_DOLPHIN_GHOST_PLAY_PPC_BASE || SUSAMUNE_DOLPHIN_GHOST_PLAY_PPC_BASE + SUSAMUNE_GHOST_SLOT_SIZE != SUSAMUNE_DOLPHIN_GHOST_TRANSFER_PPC_BASE
#error "Dolphin ghost slots must be adjacent"
#endif
#if SUSAMUNE_DOLPHIN_PERSIST_PPC_BASE < SUSAMUNE_DOLPHIN_RUNTIME_PPC_BASE || SUSAMUNE_DOLPHIN_PERSIST_PPC_BASE + SUSAMUNE_DOLPHIN_PERSIST_SIZE > SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE
#error "Dolphin persistence state overlaps another MEM2 window"
#endif
#if SUSAMUNE_DOLPHIN_PERSIST_PPC_BASE + SUSAMUNE_DOLPHIN_PERSIST_SIZE > SUSAMUNE_DOLPHIN_RECORDS_PPC_BASE || SUSAMUNE_DOLPHIN_RECORDS_PPC_BASE + SUSAMUNE_RECORDS_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_METADATA_PPC_BASE || SUSAMUNE_DOLPHIN_METADATA_PPC_BASE + SUSAMUNE_METADATA_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_CREATION_PPC_BASE || SUSAMUNE_DOLPHIN_CREATION_PPC_BASE + SUSAMUNE_CREATION_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_REGIONAL_PPC_BASE || SUSAMUNE_DOLPHIN_REGIONAL_PPC_BASE + SUSAMUNE_REGIONAL_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_MENU_PPC_BASE || SUSAMUNE_DOLPHIN_MENU_PPC_BASE + SUSAMUNE_MENU_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_CONFIG_PPC_BASE || SUSAMUNE_DOLPHIN_CONFIG_PPC_BASE + SUSAMUNE_CONFIG_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_FEATURE_PPC_BASE || SUSAMUNE_DOLPHIN_FEATURE_PPC_BASE + SUSAMUNE_FEATURE_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_ILING_PPC_BASE || SUSAMUNE_DOLPHIN_ILING_PPC_BASE + SUSAMUNE_ILING_RUNTIME_SIZE != SUSAMUNE_DOLPHIN_STAGE_LOADER_PPC_BASE || SUSAMUNE_DOLPHIN_STAGE_LOADER_PPC_BASE + SUSAMUNE_STAGE_LOADER_RUNTIME_SIZE != SUSAMUNE_DOLPHIN_CRASH_PPC_BASE || SUSAMUNE_DOLPHIN_CRASH_PPC_BASE + SUSAMUNE_MEM2_CRASH_SIZE != SUSAMUNE_DOLPHIN_STAGE_LOADER_QUEUE_PPC_BASE || SUSAMUNE_DOLPHIN_STAGE_LOADER_QUEUE_PPC_BASE + SUSAMUNE_STAGE_LOADER_QUEUE_SIZE > SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE
#error "Dolphin Susamune runtime windows overlap"
#endif
#if SUSAMUNE_CONSOLE_RECORDS_PPC_BASE + SUSAMUNE_RECORDS_RUNTIME_SIZE > SUSAMUNE_CONSOLE_METADATA_PPC_BASE || SUSAMUNE_CONSOLE_METADATA_PPC_BASE + SUSAMUNE_METADATA_RUNTIME_SIZE > SUSAMUNE_CONSOLE_CREATION_PPC_BASE || SUSAMUNE_CONSOLE_CREATION_PPC_BASE + SUSAMUNE_CREATION_RUNTIME_SIZE > SUSAMUNE_CONSOLE_REGIONAL_PPC_BASE || SUSAMUNE_CONSOLE_REGIONAL_PPC_BASE + SUSAMUNE_REGIONAL_RUNTIME_SIZE > SUSAMUNE_CONSOLE_MENU_PPC_BASE || SUSAMUNE_CONSOLE_MENU_PPC_BASE + SUSAMUNE_MENU_RUNTIME_SIZE > SUSAMUNE_CONSOLE_CONFIG_PPC_BASE || SUSAMUNE_CONSOLE_CONFIG_PPC_BASE + SUSAMUNE_CONFIG_RUNTIME_SIZE > SUSAMUNE_CONSOLE_FEATURE_PPC_BASE || SUSAMUNE_CONSOLE_FEATURE_PPC_BASE + SUSAMUNE_FEATURE_RUNTIME_SIZE > SUSAMUNE_CONSOLE_ILING_PPC_BASE || SUSAMUNE_CONSOLE_ILING_PPC_BASE + SUSAMUNE_ILING_RUNTIME_SIZE != SUSAMUNE_CONSOLE_STAGE_LOADER_PPC_BASE || SUSAMUNE_CONSOLE_STAGE_LOADER_PPC_BASE + SUSAMUNE_STAGE_LOADER_RUNTIME_SIZE != SUSAMUNE_CONSOLE_CRASH_PPC_BASE || SUSAMUNE_CONSOLE_CRASH_PPC_BASE + SUSAMUNE_MEM2_CRASH_SIZE != SUSAMUNE_CONSOLE_STAGE_LOADER_QUEUE_PPC_BASE || SUSAMUNE_CONSOLE_STAGE_LOADER_QUEUE_PPC_BASE + SUSAMUNE_STAGE_LOADER_QUEUE_SIZE > SUSAMUNE_MEM2_PB_LIVE_PPC_BASE
#error "console Susamune runtime windows overlap"
#endif
#if SUSAMUNE_DOLPHIN_MENU_TEXT_PPC_BASE + SUSAMUNE_MENU_TEXT_SIZE > SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE || SUSAMUNE_CONSOLE_MENU_TEXT_PPC_BASE + SUSAMUNE_MENU_TEXT_SIZE > SUSAMUNE_MEM2_PB_LIVE_PPC_BASE
#error "Stage targets and menu text exceed their runtime gap"
#endif
#if SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE + SUSAMUNE_DOLPHIN_PB_LIVE_SIZE > SUSAMUNE_DOLPHIN_RUNTIME_PPC_BASE + SUSAMUNE_DOLPHIN_RUNTIME_SIZE
#error "Dolphin live PB mirror exceeds its MEM2 window"
#endif
#if (SUSAMUNE_DOLPHIN_PERSIST_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_RECORDS_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_METADATA_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_CREATION_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_REGIONAL_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_MENU_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_CONFIG_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_FEATURE_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_ILING_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_STAGE_LOADER_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_CRASH_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_STAGE_LOADER_QUEUE_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE & 31u) != 0
#error "Dolphin runtime-state windows must be cache-line aligned"
#endif
#if (SUSAMUNE_CONSOLE_RECORDS_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_METADATA_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_CREATION_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_REGIONAL_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_MENU_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_CONFIG_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_FEATURE_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_ILING_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_STAGE_LOADER_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_CRASH_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_STAGE_LOADER_QUEUE_PPC_BASE & 31u) != 0
#error "console runtime-state windows must be cache-line aligned"
#endif
#if (SUSAMUNE_DOLPHIN_STAGE_TARGETS_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_STAGE_TARGETS_PPC_BASE & 31u) != 0
#error "Stage target persistence must be cache-line aligned"
#endif
#if (SUSAMUNE_DOLPHIN_MENU_TEXT_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_MENU_TEXT_PPC_BASE & 31u) != 0
#error "Menu text scratch must be cache-line aligned"
#endif

// Physical-to-PPC cached alias checks.
#if NIN_MEM2_DISC_CACHE_PHYS_BASE + 0x80000000u != NIN_MEM2_DISC_CACHE_PPC_BASE
#error "Invalid disc-cache PPC alias"
#endif
#if NIN_MEM2_SEGABOOT_PHYS_BASE + 0x80000000u != NIN_MEM2_SEGABOOT_PPC_BASE
#error "Invalid SegaBoot PPC alias"
#endif
#if NIN_MEM2_DIMM_PHYS_BASE + 0x80000000u != NIN_MEM2_DIMM_PPC_BASE
#error "Invalid DIMM PPC alias"
#endif
#if NIN_MEM2_DI_SCRATCH_PHYS_BASE + 0x80000000u != NIN_MEM2_DI_SCRATCH_PPC_BASE
#error "Invalid DI-scratch PPC alias"
#endif
#if NIN_MEM2_LOADER_DISC_PHYS_BASE + 0x80000000u != NIN_MEM2_LOADER_DISC_PPC_BASE
#error "Invalid loader-disc PPC alias"
#endif
#if SUSAMUNE_CONSOLE_GHOST_RECORD_PHYS_BASE + 0x80000000u != SUSAMUNE_CONSOLE_GHOST_RECORD_PPC_BASE || SUSAMUNE_CONSOLE_GHOST_PLAY_PHYS_BASE + 0x80000000u != SUSAMUNE_CONSOLE_GHOST_PLAY_PPC_BASE || SUSAMUNE_CONSOLE_GHOST_TRANSFER_PHYS_BASE + 0x80000000u != SUSAMUNE_CONSOLE_GHOST_TRANSFER_PPC_BASE
#error "Invalid console ghost-slot PPC alias"
#endif
#if NIN_MEM2_FILE_PATCH_PHYS_BASE + 0x80000000u != NIN_MEM2_FILE_PATCH_PPC_BASE
#error "Invalid file-patch PPC alias"
#endif
#if SUSAMUNE_MEM2_SNAPSHOT_PHYS_BASE + 0x80000000u != SUSAMUNE_MEM2_SNAPSHOT_PPC_BASE
#error "Invalid snapshot PPC alias"
#endif
#if SUSAMUNE_MEM2_MODBIN_PHYS_BASE + 0x80000000u != SUSAMUNE_MEM2_MODBIN_PPC_BASE
#error "Invalid mod-blob PPC alias"
#endif
#if SUSAMUNE_MEM2_CFG_PHYS_BASE + 0x80000000u != SUSAMUNE_MEM2_CFG_PPC_BASE
#error "Invalid settings-block PPC alias"
#endif
#if SUSAMUNE_CONSOLE_CRASH_PHYS_BASE + 0x80000000u != SUSAMUNE_CONSOLE_CRASH_PPC_BASE
#error "Invalid crash-mailbox PPC alias"
#endif
#if SUSAMUNE_CONSOLE_STAGE_TARGETS_PHYS_BASE + 0x80000000u != SUSAMUNE_CONSOLE_STAGE_TARGETS_PPC_BASE
#error "Invalid stage-target PPC alias"
#endif
#if NIN_MEM2_KERNEL_PHYS_BASE + 0x80000000u != NIN_MEM2_KERNEL_PPC_BASE
#error "Invalid kernel PPC alias"
#endif

#endif // SUSAMUNE_MEM2_MAP_H
