#ifndef SUSAMUNE_MEM2_MAP_H
#define SUSAMUNE_MEM2_MAP_H

// Shared Wii MEM2 layout for the PPC loader/mod and the ARM Nintendont kernel.
// ARM uses physical 0x1xxxxxxx addresses; PPC cached aliases add 0x80000000.
// Keep this file C-compatible: it is included by all three build toolchains.

// ISO images and real discs are mutually exclusive, so both readers share the
// first 3 MiB. RealDI divides it into front/drive/tail-cache subranges.
#define NIN_MEM2_DISC_CACHE_PHYS_BASE         0x11000000u
#define NIN_MEM2_DISC_CACHE_PPC_BASE          0x91000000u
#define NIN_MEM2_DISC_CACHE_SIZE              0x00300000u

// Nintendont buffers relocated below the savestate window.
#define NIN_MEM2_SEGABOOT_PHYS_BASE          0x11300000u
#define NIN_MEM2_SEGABOOT_PPC_BASE           0x91300000u
#define NIN_MEM2_SEGABOOT_SIZE               0x00100000u

#define NIN_MEM2_DIMM_PHYS_BASE              0x11400000u
#define NIN_MEM2_DIMM_PPC_BASE               0x91400000u
#define NIN_MEM2_DIMM_SIZE                   0x00300000u

/* Loader-only overlay. A normal GameCube IPL and Triforce are exclusive. */
#define SUSAMUNE_LAUNCHER_GCN_IPL_PPC_BASE   NIN_MEM2_DIMM_PPC_BASE
#define SUSAMUNE_LAUNCHER_GCN_IPL_SIZE       0x00200000u

#define NIN_MEM2_DI_SCRATCH_PHYS_BASE        0x11700000u
#define NIN_MEM2_DI_SCRATCH_PPC_BASE         0x91700000u
#define NIN_MEM2_DI_SCRATCH_SIZE             0x00080000u

// Used only by the PPC loader before control passes to the game/kernel.
#define NIN_MEM2_LOADER_DISC_PHYS_BASE       0x11780000u
#define NIN_MEM2_LOADER_DISC_PPC_BASE        0x91780000u
#define NIN_MEM2_LOADER_DISC_SIZE            0x00180000u

// Runtime ghost slots reuse the loader's disc buffer only after it has handed
// control to the game. The third slot holds doorbells, a local input tape,
// codec scratch and the secondary model heap; file payloads have their own bank.
#define SUSAMUNE_GHOST_SLOT_SIZE                0x00080000u
#define SUSAMUNE_CONSOLE_GHOST_RECORD_PHYS_BASE 0x11780000u
#define SUSAMUNE_CONSOLE_GHOST_RECORD_PPC_BASE  0x91780000u
#define SUSAMUNE_CONSOLE_GHOST_PLAY_PHYS_BASE   0x11800000u
#define SUSAMUNE_CONSOLE_GHOST_PLAY_PPC_BASE    0x91800000u
#define SUSAMUNE_CONSOLE_GHOST_TRANSFER_PHYS_BASE 0x11880000u
#define SUSAMUNE_CONSOLE_GHOST_TRANSFER_PPC_BASE 0x91880000u

// patch.bin / patch.txt handoff: the loader writes through the cached PPC
// alias and the ARM kernel consumes the same bytes through the physical alias.
#define NIN_MEM2_FILE_PATCH_PHYS_BASE        0x11900000u
#define NIN_MEM2_FILE_PATCH_PPC_BASE         0x91900000u
#define NIN_MEM2_FILE_PATCH_SIZE             0x0003F000u

// The retained patch prefix remains immutable across in-session resets.
// A new kernel advertises the separate state bank before PPC may borrow it.
#define SUSAMUNE_STATE_POOL_EXTRA_PHYS_BASE 0x1193F000u
#define SUSAMUNE_STATE_POOL_EXTRA_PPC_BASE  0x9193F000u
#define SUSAMUNE_STATE_POOL_EXTRA_SIZE      0x00200000u
#define SUSAMUNE_DOLPHIN_STATE_POOL_EXTRA_PPC_BASE 0x71910000u

// Immutable mod staging follows two teaching banks and a complete file mailbox.
#define SUSAMUNE_GHOST_INPUT_BANK_SIZE          0x000E0000u
// PPC-only state metadata follows the complete 54,000-frame input payload.
#define SUSAMUNE_STATE_METADATA_OFFSET         0x000D2F00u
#define SUSAMUNE_STATE_METADATA_RUNTIME_SIZE   0x0000D100u
#define SUSAMUNE_STATE_LIVE_PROFILE_OFFSET     0x00007000u
#define SUSAMUNE_STATE_LIVE_PROFILE_SIZE       0x00001720u
// Live scalar split statistics never rewind with a stored state.
#define SUSAMUNE_SPLIT_STATS_RUNTIME_OFFSET   0x00008720u
#define SUSAMUNE_SPLIT_STATS_RUNTIME_SIZE     0x000037A0u
#define SUSAMUNE_GHOST_INPUT_RECORD_PHYS_BASE   0x11B3F000u
#define SUSAMUNE_GHOST_INPUT_RECORD_PPC_BASE    0x91B3F000u
#define SUSAMUNE_GHOST_INPUT_PLAY_PHYS_BASE     0x11C1F000u
#define SUSAMUNE_GHOST_INPUT_PLAY_PPC_BASE      0x91C1F000u
#define SUSAMUNE_GHOST_FILE_TRANSFER_PHYS_BASE  0x11CFF000u
#define SUSAMUNE_GHOST_FILE_TRANSFER_PPC_BASE   0x91CFF000u
#define SUSAMUNE_GHOST_FILE_TRANSFER_SIZE       0x0013E000u
#define SUSAMUNE_STATE_STORAGE_PHYS_BASE        0x11E3D000u
#define SUSAMUNE_STATE_STORAGE_PPC_BASE         0x91E3D000u
#define SUSAMUNE_STATE_STORAGE_SIZE             0x00002000u
#define SUSAMUNE_DOLPHIN_STATE_STORAGE_PPC_BASE  0x714FE000u
#define SUSAMUNE_DOLPHIN_GHOST_INPUT_RECORD_PPC_BASE 0x71200000u
#define SUSAMUNE_DOLPHIN_GHOST_INPUT_PLAY_PPC_BASE   0x712E0000u
// Scalar-only display scratch in the playback bank's unused tail. The record
// bank's corresponding tail belongs to savestate metadata and is untouched.
// Both legacy 54,000 * 16 and V6 36,000 * 24 input streams end at +0xD2F00.
#define SUSAMUNE_PRESENTATION_OFFSET 0x000D3000u
#define SUSAMUNE_PRESENTATION_SIZE   0x0000D000u
#if IS_EMULATOR
#define SUSAMUNE_PRESENTATION_PPC_BASE \
    (SUSAMUNE_DOLPHIN_GHOST_INPUT_PLAY_PPC_BASE + SUSAMUNE_PRESENTATION_OFFSET)
#else
#define SUSAMUNE_PRESENTATION_PPC_BASE \
    (SUSAMUNE_GHOST_INPUT_PLAY_PPC_BASE + SUSAMUNE_PRESENTATION_OFFSET)
#endif
#define SUSAMUNE_NATIVE_TIMER_DRAW_PPC_BASE SUSAMUNE_PRESENTATION_PPC_BASE
#define SUSAMUNE_HSL_CACHE_PPC_BASE (SUSAMUNE_PRESENTATION_PPC_BASE + 0x1600u)
#define SUSAMUNE_GHOST_WATER_PPC_BASE (SUSAMUNE_PRESENTATION_PPC_BASE + 0x2000u)
#define SUSAMUNE_GHOST_WATER_SIZE 0x2000u
#if SUSAMUNE_PRESENTATION_OFFSET + SUSAMUNE_PRESENTATION_SIZE != SUSAMUNE_GHOST_INPUT_BANK_SIZE || SUSAMUNE_PRESENTATION_OFFSET < 54000u * 16u
#error Presentation scratch overlaps legacy ghost input or exceeds its bank
#endif
#define SUSAMUNE_CONSOLE_STATE_METADATA_PPC_BASE     (SUSAMUNE_GHOST_INPUT_RECORD_PPC_BASE + SUSAMUNE_STATE_METADATA_OFFSET)
#define SUSAMUNE_DOLPHIN_STATE_METADATA_PPC_BASE     (SUSAMUNE_DOLPHIN_GHOST_INPUT_RECORD_PPC_BASE + SUSAMUNE_STATE_METADATA_OFFSET)
#define SUSAMUNE_CONSOLE_SPLIT_STATS_RUNTIME_PPC_BASE (SUSAMUNE_CONSOLE_STATE_METADATA_PPC_BASE + SUSAMUNE_SPLIT_STATS_RUNTIME_OFFSET)
#define SUSAMUNE_DOLPHIN_SPLIT_STATS_RUNTIME_PPC_BASE (SUSAMUNE_DOLPHIN_STATE_METADATA_PPC_BASE + SUSAMUNE_SPLIT_STATS_RUNTIME_OFFSET)
#if SUSAMUNE_STATE_METADATA_OFFSET + SUSAMUNE_STATE_METADATA_RUNTIME_SIZE != SUSAMUNE_GHOST_INPUT_BANK_SIZE || (SUSAMUNE_STATE_METADATA_OFFSET & 31u) || (SUSAMUNE_STATE_METADATA_RUNTIME_SIZE & 31u)
#error "state metadata must own the aligned recording-input tail"
#endif
#if SUSAMUNE_STATE_LIVE_PROFILE_OFFSET + SUSAMUNE_STATE_LIVE_PROFILE_SIZE > SUSAMUNE_STATE_METADATA_RUNTIME_SIZE || (SUSAMUNE_STATE_LIVE_PROFILE_OFFSET & 31u) || (SUSAMUNE_STATE_LIVE_PROFILE_SIZE & 31u)
#error "live state owner profile must fit the aligned metadata tail"
#endif
#if SUSAMUNE_STATE_LIVE_PROFILE_OFFSET + SUSAMUNE_STATE_LIVE_PROFILE_SIZE > SUSAMUNE_SPLIT_STATS_RUNTIME_OFFSET || SUSAMUNE_SPLIT_STATS_RUNTIME_OFFSET + SUSAMUNE_SPLIT_STATS_RUNTIME_SIZE > SUSAMUNE_STATE_METADATA_RUNTIME_SIZE || (SUSAMUNE_SPLIT_STATS_RUNTIME_OFFSET & 31u) || (SUSAMUNE_SPLIT_STATS_RUNTIME_SIZE & 31u)
#error "live split statistics must fit after the owner profile in the aligned metadata tail"
#endif
#define SUSAMUNE_DOLPHIN_GHOST_FILE_TRANSFER_PPC_BASE 0x713C0000u

// mod_<region>.bin staging (struct SusamuneModHeader, mod_bin.h). The PPC
// loader reads the file for the detected disc here before booting the kernel;
// PatchSusamune() copies the code out into MEM1. PatchGame can consume this
// staging prefix again after an in-session reset, so it remains immutable.
//
// The patch tail holds 3 MiB of ghost teaching buffers, then this 772 KiB
// staging/vault allocation. The remaining generic patch prefix stays bounded;
// neither reset-safe staging nor savestate storage may be borrowed at runtime.
#define SUSAMUNE_MEM2_MODBIN_PHYS_BASE       0x11E3F000u
#define SUSAMUNE_MEM2_MODBIN_PPC_BASE        0x91E3F000u
#define SUSAMUNE_MEM2_MODBIN_SIZE            0x000C1000u

// PatchGame can consume the staged mod again after an in-session reset. The
// file may use the complete prefix before the immutable model-asset vault.
#define SUSAMUNE_MOD_STAGED_FILE_MAX_SIZE         0x0009F000u

// PatchSusamune consumes the complete mod staging file before the kernel
// publishes immutable retail model assets into its now-dead tail.
#define SUSAMUNE_GHOST_ASSET_VAULT_OFFSET         0x0009F000u
#define SUSAMUNE_GHOST_SHADOW_MASTER_OFFSET       0x00000000u
#define SUSAMUNE_GHOST_SHADOW_MASTER_SIZE         0x00010000u
#define SUSAMUNE_GHOST_PIANTA_MASTER_OFFSET       0x00010000u
#define SUSAMUNE_GHOST_PIANTA_MASTER_SIZE         0x00012000u
#define SUSAMUNE_GHOST_ASSET_VAULT_SIZE           0x00022000u
#define SUSAMUNE_GHOST_ASSET_VAULT_PHYS_BASE \
    (SUSAMUNE_MEM2_MODBIN_PHYS_BASE + SUSAMUNE_GHOST_ASSET_VAULT_OFFSET)
#define SUSAMUNE_GHOST_ASSET_VAULT_PPC_BASE \
    (SUSAMUNE_MEM2_MODBIN_PPC_BASE + SUSAMUNE_GHOST_ASSET_VAULT_OFFSET)

// Dedicated Susamune snapshot window. No Nintendont buffer may overlap this
// range. Its exclusive end is the settings block below.
#define SUSAMUNE_MEM2_SNAPSHOT_PHYS_BASE     0x11F00000u
#define SUSAMUNE_MEM2_SNAPSHOT_PPC_BASE      0x91F00000u
#define SUSAMUNE_MEM2_SNAPSHOT_SIZE          0x00FF0000u

/* New kernels move codec scratch to the former ghost-transfer gap. */
#define SUSAMUNE_STATE_CODEC_WORKSPACE_SIZE  0x0004E000u
#define SUSAMUNE_STATE_POOL_LEGACY_SIZE \
    (SUSAMUNE_MEM2_SNAPSHOT_SIZE - SUSAMUNE_STATE_CODEC_WORKSPACE_SIZE)
#define SUSAMUNE_STATE_POOL_SIZE SUSAMUNE_MEM2_SNAPSHOT_SIZE
#define SUSAMUNE_STATE_POOL_EXPANDED_SIZE \
    (SUSAMUNE_STATE_POOL_SIZE + SUSAMUNE_STATE_POOL_EXTRA_SIZE)

/* Sunshine-only scratch after IPL/Triforce handoff. RAM save owns it until
 * commit; SD import owns it through its receipt and validation. Never a slot. */
#define SUSAMUNE_STATE_STAGING_PPC_BASE      NIN_MEM2_SEGABOOT_PPC_BASE
#define SUSAMUNE_STATE_STAGING_SIZE          0x00400000u
#define SUSAMUNE_DOLPHIN_STATE_STAGING_PPC_BASE 0x71500000u
#if SUSAMUNE_STATE_STAGING_PPC_BASE + SUSAMUNE_STATE_STAGING_SIZE != NIN_MEM2_DI_SCRATCH_PPC_BASE
#error State save staging exceeds the retired IPL/Triforce buffers
#endif
#if SUSAMUNE_DOLPHIN_STATE_STORAGE_PPC_BASE != SUSAMUNE_DOLPHIN_GHOST_FILE_TRANSFER_PPC_BASE + SUSAMUNE_GHOST_FILE_TRANSFER_SIZE || SUSAMUNE_DOLPHIN_STATE_STAGING_PPC_BASE != SUSAMUNE_DOLPHIN_STATE_STORAGE_PPC_BASE + SUSAMUNE_STATE_STORAGE_SIZE
#error Dolphin state mailbox must separate ghost transfer and state staging
#endif
#if SUSAMUNE_DOLPHIN_STATE_STAGING_PPC_BASE + SUSAMUNE_STATE_STAGING_SIZE > 0x72000000u
#error Dolphin state staging exceeds the emulated aperture
#endif

/* Loader-only overlay. Music stops before the game can create a snapshot. */
#define SUSAMUNE_LAUNCHER_MUSIC_PPC_BASE     SUSAMUNE_MEM2_SNAPSHOT_PPC_BASE
#define SUSAMUNE_LAUNCHER_MUSIC_SIZE         0x00400000u

// Dolphin exposes a separate 16 MiB aperture for the snapshot. Keep its final
// 64 KiB outside the snapshot payload for live emulator-only state; unlike the
// Wii addresses below, nothing on the ARM side consumes these bytes.
#define SUSAMUNE_DOLPHIN_SNAPSHOT_PPC_BASE   0x70000000u
#define SUSAMUNE_DOLPHIN_RUNTIME_PPC_BASE    0x70FF0000u
#define SUSAMUNE_DOLPHIN_RUNTIME_SIZE        0x00010000u
#define SUSAMUNE_DOLPHIN_PERSIST_PPC_BASE    0x70FF0000u
#define SUSAMUNE_DOLPHIN_PERSIST_SIZE        0x00001800u
#define SUSAMUNE_DOLPHIN_RECORDS_PPC_BASE    0x70FF1800u
#define SUSAMUNE_DOLPHIN_METADATA_PPC_BASE   0x70FF2000u
#define SUSAMUNE_DOLPHIN_CREATION_PPC_BASE   0x70FF2800u
#define SUSAMUNE_DOLPHIN_REGIONAL_PPC_BASE   0x70FF2D00u
#define SUSAMUNE_DOLPHIN_MENU_PPC_BASE       0x70FF2F00u
#define SUSAMUNE_DOLPHIN_CONFIG_PPC_BASE     0x70FF3300u
#define SUSAMUNE_DOLPHIN_FEATURE_PPC_BASE    0x70FF3500u
#define SUSAMUNE_DOLPHIN_ILING_PPC_BASE      0x70FF3600u
#define SUSAMUNE_DOLPHIN_STAGE_LOADER_PPC_BASE 0x70FF3700u
#define SUSAMUNE_DOLPHIN_CRASH_PPC_BASE      0x70FF3800u
#define SUSAMUNE_DOLPHIN_STAGE_LOADER_QUEUE_PPC_BASE 0x70FF4800u
#define SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE    0x70FFF780u
#define SUSAMUNE_DOLPHIN_PB_LIVE_SIZE        0x00000880u

// Keep Dolphin's ghost slots in the same three-slot shape as console.
#define SUSAMUNE_DOLPHIN_GHOST_RECORD_PPC_BASE  0x71000000u
#define SUSAMUNE_DOLPHIN_GHOST_PLAY_PPC_BASE    0x71080000u
#define SUSAMUNE_DOLPHIN_GHOST_TRANSFER_PPC_BASE 0x71100000u

// J3D allocations for the visual-only ghost live in the unused gap between
// the maximum 15-minute sample payload and the V2 segment table. The fixed
// heap has 0x15ed0 usable bytes; Shadow Mario's checked bound is 0x12000.
#define SUSAMUNE_GHOST_MODEL_HEAP_OFFSET          0x000695E0u
#define SUSAMUNE_GHOST_MODEL_HEAP_SIZE            0x00016000u
#define SUSAMUNE_GHOST_CATALOG_CACHE_OFFSET        0x000795E0u
#define SUSAMUNE_GHOST_CATALOG_CACHE_SIZE          0x00001E00u
#define SUSAMUNE_GHOST_SEGMENT_TABLE_OFFSET       0x0007F800u
#define SUSAMUNE_GHOST_TRANSFER_MAILBOX_HEADER_SIZE 0x00000100u
#define SUSAMUNE_GHOST_SECONDARY_HEAP_OFFSET      0x0006A000u
#define SUSAMUNE_GHOST_SECONDARY_HEAP_SIZE        0x00016000u

// Protocol 4 moved file payloads out of this PPC-only runtime window.
#define SUSAMUNE_PRACTICE_TAPE_OFFSET             0x00000100u
#define SUSAMUNE_PRACTICE_TAPE_SIZE               0x00010000u
#define SUSAMUNE_CONSOLE_PRACTICE_TAPE_PHYS_BASE \
    (SUSAMUNE_CONSOLE_GHOST_TRANSFER_PHYS_BASE + SUSAMUNE_PRACTICE_TAPE_OFFSET)
#define SUSAMUNE_CONSOLE_PRACTICE_TAPE_PPC_BASE \
    (SUSAMUNE_CONSOLE_GHOST_TRANSFER_PPC_BASE + SUSAMUNE_PRACTICE_TAPE_OFFSET)
#define SUSAMUNE_DOLPHIN_PRACTICE_TAPE_PPC_BASE \
    (SUSAMUNE_DOLPHIN_GHOST_TRANSFER_PPC_BASE + SUSAMUNE_PRACTICE_TAPE_OFFSET)

// Shared split-statistics mailbox, above scratch and below the second model heap.
#define SUSAMUNE_SPLIT_STATS_MAILBOX_OFFSET 0x0005F000u
#define SUSAMUNE_SPLIT_STATS_MAILBOX_SIZE   0x0000B000u
#define SUSAMUNE_CONSOLE_SPLIT_STATS_PHYS_BASE \
    (SUSAMUNE_CONSOLE_GHOST_TRANSFER_PHYS_BASE + SUSAMUNE_SPLIT_STATS_MAILBOX_OFFSET)
#define SUSAMUNE_CONSOLE_SPLIT_STATS_PPC_BASE \
    (SUSAMUNE_CONSOLE_GHOST_TRANSFER_PPC_BASE + SUSAMUNE_SPLIT_STATS_MAILBOX_OFFSET)
#define SUSAMUNE_DOLPHIN_SPLIT_STATS_PPC_BASE \
    (SUSAMUNE_DOLPHIN_GHOST_TRANSFER_PPC_BASE + SUSAMUNE_SPLIT_STATS_MAILBOX_OFFSET)

#define SUSAMUNE_STATE_CODEC_WORKSPACE_OFFSET 0x00011000u
#define SUSAMUNE_CONSOLE_STATE_CODEC_PPC_BASE \
    (SUSAMUNE_CONSOLE_GHOST_TRANSFER_PPC_BASE + SUSAMUNE_STATE_CODEC_WORKSPACE_OFFSET)
#define SUSAMUNE_DOLPHIN_STATE_CODEC_PPC_BASE \
    (SUSAMUNE_DOLPHIN_GHOST_TRANSFER_PPC_BASE + SUSAMUNE_STATE_CODEC_WORKSPACE_OFFSET)

// Settings/PB handoff block (struct SusamuneCfg, susamune_cfg.h). The ARM
// kernel fills it before boot and services the mod's independent ini and PB
// save doorbells. Carved off the top of the snapshot window rather than from
// Nintendont's buffers, since the snapshot's 16 MiB reservation is far larger
// than its use. Deliberately outside the snapshot payload so a savestate load
// does not rewind persistent data.
#define SUSAMUNE_MEM2_CFG_PHYS_BASE          0x12EF0000u
#define SUSAMUNE_MEM2_CFG_PPC_BASE           0x92EF0000u
#define SUSAMUNE_MEM2_CFG_SIZE               0x00010000u

// Runtime state lives after the progress mailbox and before the live PB
// mirror. Only the crash mailbox is shared back to the ARM kernel.
#define SUSAMUNE_CONSOLE_RECORDS_PPC_BASE    0x92EF2400u
#define SUSAMUNE_CONSOLE_METADATA_PPC_BASE   0x92EF2C00u
#define SUSAMUNE_CONSOLE_CREATION_PPC_BASE   0x92EF3400u
#define SUSAMUNE_CONSOLE_REGIONAL_PPC_BASE   0x92EF3900u
#define SUSAMUNE_CONSOLE_MENU_PPC_BASE       0x92EF3B00u
#define SUSAMUNE_CONSOLE_CONFIG_PPC_BASE     0x92EF3F00u
#define SUSAMUNE_CONSOLE_FEATURE_PPC_BASE    0x92EF4100u
#define SUSAMUNE_CONSOLE_ILING_PPC_BASE      0x92EF4200u
#define SUSAMUNE_CONSOLE_STAGE_LOADER_PPC_BASE 0x92EF4300u
#define SUSAMUNE_CONSOLE_CRASH_PHYS_BASE     0x12EF4400u
#define SUSAMUNE_CONSOLE_CRASH_PPC_BASE      0x92EF4400u
#define SUSAMUNE_CONSOLE_STAGE_LOADER_QUEUE_PPC_BASE 0x92EF5400u

#define SUSAMUNE_RECORDS_RUNTIME_SIZE         0x00000800u
#define SUSAMUNE_METADATA_RUNTIME_SIZE        0x00000800u
#define SUSAMUNE_CREATION_RUNTIME_SIZE        0x00000500u
#define SUSAMUNE_REGIONAL_RUNTIME_SIZE        0x00000200u
#define SUSAMUNE_MENU_RUNTIME_SIZE            0x00000400u
#define SUSAMUNE_CONFIG_RUNTIME_SIZE          0x00000200u
#define SUSAMUNE_FEATURE_RUNTIME_SIZE         0x00000100u
#define SUSAMUNE_ILING_RUNTIME_SIZE           0x00000100u
#define SUSAMUNE_STAGE_LOADER_RUNTIME_SIZE    0x00000100u
#define SUSAMUNE_MEM2_CRASH_SIZE              0x00001000u
#define SUSAMUNE_STAGE_LOADER_QUEUE_SIZE       0x00000100u
#define SUSAMUNE_STAGE_TARGETS_CFG_SIZE         0x00000260u
#define SUSAMUNE_STAGE_TARGETS_LIVE_SIZE        0x00000220u
#define SUSAMUNE_MENU_TEXT_SIZE                 0x00000200u

// Stage Loader targets occupy the low end of the otherwise-unused gap before
// the split-statistics mailbox. Derive both ends so schema growth cannot
// overlap them.
#define SUSAMUNE_CONSOLE_STAGE_TARGETS_PPC_BASE \
    (SUSAMUNE_CONSOLE_STAGE_LOADER_QUEUE_PPC_BASE + \
     SUSAMUNE_STAGE_LOADER_QUEUE_SIZE)
#define SUSAMUNE_CONSOLE_STAGE_TARGETS_PHYS_BASE \
    (SUSAMUNE_CONSOLE_STAGE_TARGETS_PPC_BASE - 0x80000000u)
#define SUSAMUNE_DOLPHIN_STAGE_TARGETS_PPC_BASE \
    (SUSAMUNE_DOLPHIN_STAGE_LOADER_QUEUE_PPC_BASE + \
     SUSAMUNE_STAGE_LOADER_QUEUE_SIZE)
#define SUSAMUNE_CONSOLE_MENU_TEXT_PPC_BASE \
    (SUSAMUNE_CONSOLE_STAGE_TARGETS_PPC_BASE + \
     SUSAMUNE_STAGE_TARGETS_CFG_SIZE + SUSAMUNE_STAGE_TARGETS_LIVE_SIZE)
#define SUSAMUNE_DOLPHIN_MENU_TEXT_PPC_BASE \
    (SUSAMUNE_DOLPHIN_STAGE_TARGETS_PPC_BASE + \
     SUSAMUNE_STAGE_TARGETS_CFG_SIZE + SUSAMUNE_STAGE_TARGETS_LIVE_SIZE)

#define SUSAMUNE_CONFIG_SETTINGS_OFFSET       0x00000000u
#define SUSAMUNE_CONFIG_SETTINGS_SIZE         0x00000088u
#define SUSAMUNE_CONFIG_BINDS_OFFSET          0x00000088u
#define SUSAMUNE_CONFIG_BINDS_SIZE            0x00000038u
#define SUSAMUNE_FOXTROT_BINDS_SIZE 0x80u
#define SUSAMUNE_FOXTROT_SETTINGS_SIZE 0x100u
#define SUSAMUNE_FOXTROT_MENU_RUNTIME_SIZE 0x800u
#define SUSAMUNE_CONFIG_INPUT_OFFSET          0x000000C0u
#define SUSAMUNE_CONFIG_INPUT_SIZE            0x000000A0u
#define SUSAMUNE_CONFIG_QFT_OFFSET            0x00000160u
#define SUSAMUNE_CONFIG_QFT_SIZE              0x00000080u
#define SUSAMUNE_CONFIG_ATTEMPTS_OFFSET       0x000001E0u
#define SUSAMUNE_CONFIG_ATTEMPTS_SIZE         0x00000020u

#if IS_EMULATOR
#define SUSAMUNE_MEM2_RECORDS_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_RECORDS_PPC_BASE
#define SUSAMUNE_MEM2_METADATA_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_METADATA_PPC_BASE
#define SUSAMUNE_MEM2_CREATION_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_CREATION_PPC_BASE
#define SUSAMUNE_MEM2_REGIONAL_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_REGIONAL_PPC_BASE
#define SUSAMUNE_MEM2_MENU_RUNTIME_PPC_BASE 0x70FF6000u
#define SUSAMUNE_MEM2_BINDS_RUNTIME_PPC_BASE 0x70FF5B80u
#define SUSAMUNE_MEM2_SETTINGS_RUNTIME_PPC_BASE 0x70FF5C00u
#define SUSAMUNE_MEM2_CONFIG_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_CONFIG_PPC_BASE
#define SUSAMUNE_MEM2_FEATURE_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_FEATURE_PPC_BASE
#define SUSAMUNE_MEM2_ILING_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_ILING_PPC_BASE
#define SUSAMUNE_MEM2_STAGE_LOADER_RUNTIME_PPC_BASE \
    SUSAMUNE_DOLPHIN_STAGE_LOADER_PPC_BASE
#define SUSAMUNE_MEM2_CRASH_PPC_BASE SUSAMUNE_DOLPHIN_CRASH_PPC_BASE
#define SUSAMUNE_MEM2_CRASH_PHYS_BASE \
    (SUSAMUNE_DOLPHIN_CRASH_PPC_BASE - 0x60000000u)
#define SUSAMUNE_MEM2_STAGE_LOADER_QUEUE_PPC_BASE \
    SUSAMUNE_DOLPHIN_STAGE_LOADER_QUEUE_PPC_BASE
#define SUSAMUNE_MEM2_STAGE_TARGETS_PPC_BASE \
    SUSAMUNE_DOLPHIN_STAGE_TARGETS_PPC_BASE
#define SUSAMUNE_MEM2_MENU_TEXT_PPC_BASE \
    SUSAMUNE_DOLPHIN_MENU_TEXT_PPC_BASE
#define SUSAMUNE_GHOST_RECORD_PPC_BASE SUSAMUNE_DOLPHIN_GHOST_RECORD_PPC_BASE
#define SUSAMUNE_GHOST_PLAY_PPC_BASE SUSAMUNE_DOLPHIN_GHOST_PLAY_PPC_BASE
#define SUSAMUNE_GHOST_TRANSFER_PPC_BASE SUSAMUNE_DOLPHIN_GHOST_TRANSFER_PPC_BASE
#define SUSAMUNE_PRACTICE_TAPE_PPC_BASE SUSAMUNE_DOLPHIN_PRACTICE_TAPE_PPC_BASE
#define SUSAMUNE_STATE_CODEC_PPC_BASE SUSAMUNE_DOLPHIN_STATE_CODEC_PPC_BASE
#define SUSAMUNE_STATE_METADATA_PPC_BASE SUSAMUNE_DOLPHIN_STATE_METADATA_PPC_BASE
#define SUSAMUNE_SPLIT_STATS_RUNTIME_PPC_BASE SUSAMUNE_DOLPHIN_SPLIT_STATS_RUNTIME_PPC_BASE
#else
#define SUSAMUNE_MEM2_RECORDS_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_RECORDS_PPC_BASE
#define SUSAMUNE_MEM2_METADATA_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_METADATA_PPC_BASE
#define SUSAMUNE_MEM2_CREATION_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_CREATION_PPC_BASE
#define SUSAMUNE_MEM2_REGIONAL_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_REGIONAL_PPC_BASE
#define SUSAMUNE_MEM2_MENU_RUNTIME_PPC_BASE 0x92EF6000u
#define SUSAMUNE_MEM2_BINDS_RUNTIME_PPC_BASE 0x92EF5B80u
#define SUSAMUNE_MEM2_SETTINGS_RUNTIME_PPC_BASE 0x92EF5C00u
#define SUSAMUNE_MEM2_CONFIG_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_CONFIG_PPC_BASE
#define SUSAMUNE_MEM2_FEATURE_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_FEATURE_PPC_BASE
#define SUSAMUNE_MEM2_ILING_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_ILING_PPC_BASE
#define SUSAMUNE_MEM2_STAGE_LOADER_RUNTIME_PPC_BASE \
    SUSAMUNE_CONSOLE_STAGE_LOADER_PPC_BASE
#define SUSAMUNE_MEM2_CRASH_PPC_BASE SUSAMUNE_CONSOLE_CRASH_PPC_BASE
#define SUSAMUNE_MEM2_CRASH_PHYS_BASE SUSAMUNE_CONSOLE_CRASH_PHYS_BASE
#define SUSAMUNE_MEM2_STAGE_LOADER_QUEUE_PPC_BASE \
    SUSAMUNE_CONSOLE_STAGE_LOADER_QUEUE_PPC_BASE
#define SUSAMUNE_MEM2_STAGE_TARGETS_PPC_BASE \
    SUSAMUNE_CONSOLE_STAGE_TARGETS_PPC_BASE
#define SUSAMUNE_MEM2_MENU_TEXT_PPC_BASE \
    SUSAMUNE_CONSOLE_MENU_TEXT_PPC_BASE
#define SUSAMUNE_GHOST_RECORD_PPC_BASE SUSAMUNE_CONSOLE_GHOST_RECORD_PPC_BASE
#define SUSAMUNE_GHOST_PLAY_PPC_BASE SUSAMUNE_CONSOLE_GHOST_PLAY_PPC_BASE
#define SUSAMUNE_GHOST_TRANSFER_PPC_BASE SUSAMUNE_CONSOLE_GHOST_TRANSFER_PPC_BASE
#define SUSAMUNE_PRACTICE_TAPE_PPC_BASE SUSAMUNE_CONSOLE_PRACTICE_TAPE_PPC_BASE
#define SUSAMUNE_STATE_CODEC_PPC_BASE SUSAMUNE_CONSOLE_STATE_CODEC_PPC_BASE
#define SUSAMUNE_STATE_METADATA_PPC_BASE SUSAMUNE_CONSOLE_STATE_METADATA_PPC_BASE
#define SUSAMUNE_SPLIT_STATS_RUNTIME_PPC_BASE SUSAMUNE_CONSOLE_SPLIT_STATS_RUNTIME_PPC_BASE
#endif

#define SUSAMUNE_GHOST_MODEL_HEAP_PPC_BASE \
    (SUSAMUNE_GHOST_PLAY_PPC_BASE + SUSAMUNE_GHOST_MODEL_HEAP_OFFSET)
#define SUSAMUNE_GHOST_CATALOG_CACHE_PPC_BASE \
    (SUSAMUNE_GHOST_RECORD_PPC_BASE + SUSAMUNE_GHOST_CATALOG_CACHE_OFFSET)
#define SUSAMUNE_GHOST_SECONDARY_HEAP_PPC_BASE \
    (SUSAMUNE_GHOST_TRANSFER_PPC_BASE + \
     SUSAMUNE_GHOST_SECONDARY_HEAP_OFFSET)
#if SUSAMUNE_GHOST_MODEL_HEAP_OFFSET + SUSAMUNE_GHOST_MODEL_HEAP_SIZE > SUSAMUNE_GHOST_SEGMENT_TABLE_OFFSET
#error "ghost model heap overlaps the playback segment table"
#endif
#if SUSAMUNE_GHOST_CATALOG_CACHE_OFFSET + SUSAMUNE_GHOST_CATALOG_CACHE_SIZE > SUSAMUNE_GHOST_SEGMENT_TABLE_OFFSET
#error "ghost catalog cache overlaps the recording segment table"
#endif
#if (SUSAMUNE_GHOST_CATALOG_CACHE_OFFSET & 31u) != 0 || (SUSAMUNE_GHOST_CATALOG_CACHE_SIZE & 31u) != 0
#error "ghost catalog cache must be cache-line aligned"
#endif
#if SUSAMUNE_GHOST_SECONDARY_HEAP_OFFSET + SUSAMUNE_GHOST_SECONDARY_HEAP_SIZE != SUSAMUNE_GHOST_SLOT_SIZE
#error "secondary ghost model heap must exactly consume the transfer tail"
#endif
#if (SUSAMUNE_GHOST_SECONDARY_HEAP_OFFSET & 31u) != 0 || (SUSAMUNE_GHOST_SECONDARY_HEAP_SIZE & 31u) != 0
#error "ghost transfer/model boundaries must be cache-line aligned"
#endif
#if SUSAMUNE_PRACTICE_TAPE_OFFSET < SUSAMUNE_GHOST_TRANSFER_MAILBOX_HEADER_SIZE || SUSAMUNE_PRACTICE_TAPE_OFFSET + SUSAMUNE_PRACTICE_TAPE_SIZE > SUSAMUNE_STATE_CODEC_WORKSPACE_OFFSET
#error "practice tape overlaps ghost doorbells or secondary model heap"
#endif
#if SUSAMUNE_STATE_CODEC_WORKSPACE_OFFSET + SUSAMUNE_STATE_CODEC_WORKSPACE_SIZE > SUSAMUNE_SPLIT_STATS_MAILBOX_OFFSET || (SUSAMUNE_STATE_CODEC_WORKSPACE_OFFSET & 31u) || (SUSAMUNE_STATE_CODEC_WORKSPACE_SIZE & 31u)
#error "state codec scratch overlaps the secondary model heap or shares cache lines"
#endif
#if SUSAMUNE_STATE_POOL_LEGACY_SIZE + SUSAMUNE_STATE_CODEC_WORKSPACE_SIZE != SUSAMUNE_STATE_POOL_SIZE || SUSAMUNE_STATE_POOL_SIZE != SUSAMUNE_MEM2_SNAPSHOT_SIZE
#error "state pool and legacy codec scratch exceed the snapshot window"
#endif
#if (SUSAMUNE_CONSOLE_PRACTICE_TAPE_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_PRACTICE_TAPE_PPC_BASE & 31u) != 0 || (SUSAMUNE_PRACTICE_TAPE_SIZE & 31u) != 0
#error "practice tape must own complete cache lines"
#endif
#if SUSAMUNE_CONSOLE_PRACTICE_TAPE_PHYS_BASE + 0x80000000u != SUSAMUNE_CONSOLE_PRACTICE_TAPE_PPC_BASE
#error "invalid practice tape PPC alias"
#endif
#if SUSAMUNE_GHOST_ASSET_VAULT_OFFSET + SUSAMUNE_GHOST_ASSET_VAULT_SIZE != SUSAMUNE_MEM2_MODBIN_SIZE || SUSAMUNE_GHOST_SHADOW_MASTER_OFFSET + SUSAMUNE_GHOST_SHADOW_MASTER_SIZE != SUSAMUNE_GHOST_PIANTA_MASTER_OFFSET || SUSAMUNE_GHOST_PIANTA_MASTER_OFFSET + SUSAMUNE_GHOST_PIANTA_MASTER_SIZE != SUSAMUNE_GHOST_ASSET_VAULT_SIZE
#error "ghost model asset vault must exactly consume the mod staging tail"
#endif
#if SUSAMUNE_MOD_STAGED_FILE_MAX_SIZE != SUSAMUNE_GHOST_ASSET_VAULT_OFFSET
#error "staged mod file must end at the immutable asset vault"
#endif

#if SUSAMUNE_CONFIG_SETTINGS_OFFSET + SUSAMUNE_CONFIG_SETTINGS_SIZE > SUSAMUNE_CONFIG_BINDS_OFFSET || SUSAMUNE_CONFIG_BINDS_OFFSET + SUSAMUNE_CONFIG_BINDS_SIZE > SUSAMUNE_CONFIG_INPUT_OFFSET || SUSAMUNE_CONFIG_INPUT_OFFSET + SUSAMUNE_CONFIG_INPUT_SIZE > SUSAMUNE_CONFIG_QFT_OFFSET || SUSAMUNE_CONFIG_QFT_OFFSET + SUSAMUNE_CONFIG_QFT_SIZE > SUSAMUNE_CONFIG_ATTEMPTS_OFFSET || SUSAMUNE_CONFIG_ATTEMPTS_OFFSET + SUSAMUNE_CONFIG_ATTEMPTS_SIZE > SUSAMUNE_CONFIG_RUNTIME_SIZE
#error "Susamune configuration runtime slots overlap"
#endif

// PPC-only live PB profiles. The ARM doorbell payload remains immutable while
// a save is in flight; later PB changes queue here for the next write.
#define SUSAMUNE_MEM2_PB_LIVE_PPC_BASE       0x92EFF780u
#define SUSAMUNE_MEM2_PB_LIVE_SIZE           0x00000880u

#define SUSAMUNE_MEM2_STAGE_TARGETS_LIVE_PPC_BASE \
    (SUSAMUNE_MEM2_STAGE_TARGETS_PPC_BASE + SUSAMUNE_STAGE_TARGETS_CFG_SIZE)

#define NIN_MEM2_KERNEL_PHYS_BASE            0x12F00000u
#define NIN_MEM2_KERNEL_PPC_BASE             0x92F00000u
// The loadable code/data image stops where kernel.ld starts ARM stacks.
#define NIN_MEM2_KERNEL_IMAGE_SIZE           0x000E0000u

// Compile-time adjacency checks. Besides documenting the intended ownership,
// these prevent a future size/address edit from silently entering the snapshot.
#if NIN_MEM2_DISC_CACHE_PHYS_BASE + NIN_MEM2_DISC_CACHE_SIZE != NIN_MEM2_SEGABOOT_PHYS_BASE
#error "MEM2 map gap/overlap between disc cache and SegaBoot"
#endif
#if NIN_MEM2_SEGABOOT_PHYS_BASE + NIN_MEM2_SEGABOOT_SIZE != NIN_MEM2_DIMM_PHYS_BASE
#error "MEM2 map gap/overlap between SegaBoot and DIMM buffers"
#endif
#if NIN_MEM2_DIMM_PHYS_BASE + NIN_MEM2_DIMM_SIZE != NIN_MEM2_DI_SCRATCH_PHYS_BASE
#error "MEM2 map gap/overlap between DIMM and DI scratch buffers"
#endif
#if NIN_MEM2_DI_SCRATCH_PPC_BASE + NIN_MEM2_DI_SCRATCH_SIZE != NIN_MEM2_LOADER_DISC_PPC_BASE
#error "MEM2 map gap/overlap before the loader disc buffer"
#endif
#if NIN_MEM2_LOADER_DISC_PPC_BASE + NIN_MEM2_LOADER_DISC_SIZE != NIN_MEM2_FILE_PATCH_PPC_BASE
#error "MEM2 map gap/overlap before the file-patch buffer"
#endif
#if SUSAMUNE_CONSOLE_GHOST_RECORD_PPC_BASE != NIN_MEM2_LOADER_DISC_PPC_BASE || SUSAMUNE_CONSOLE_GHOST_RECORD_PPC_BASE + SUSAMUNE_GHOST_SLOT_SIZE != SUSAMUNE_CONSOLE_GHOST_PLAY_PPC_BASE || SUSAMUNE_CONSOLE_GHOST_PLAY_PPC_BASE + SUSAMUNE_GHOST_SLOT_SIZE != SUSAMUNE_CONSOLE_GHOST_TRANSFER_PPC_BASE || SUSAMUNE_CONSOLE_GHOST_TRANSFER_PPC_BASE + SUSAMUNE_GHOST_SLOT_SIZE != NIN_MEM2_FILE_PATCH_PPC_BASE
#error "console ghost slots must exactly tile the loader disc buffer"
#endif
#if NIN_MEM2_FILE_PATCH_PHYS_BASE + NIN_MEM2_FILE_PATCH_SIZE != SUSAMUNE_STATE_POOL_EXTRA_PHYS_BASE || SUSAMUNE_STATE_POOL_EXTRA_PHYS_BASE + SUSAMUNE_STATE_POOL_EXTRA_SIZE != SUSAMUNE_GHOST_INPUT_RECORD_PHYS_BASE
#error "MEM2 file-patch buffer must end before ghost teaching data"
#endif
#if SUSAMUNE_MEM2_MODBIN_PHYS_BASE + SUSAMUNE_MEM2_MODBIN_SIZE != SUSAMUNE_MEM2_SNAPSHOT_PHYS_BASE
#error "MEM2 mod-blob staging area must end at the snapshot window"
#endif
#if SUSAMUNE_MEM2_SNAPSHOT_PHYS_BASE + SUSAMUNE_MEM2_SNAPSHOT_SIZE != SUSAMUNE_MEM2_CFG_PHYS_BASE
#error "MEM2 snapshot window must end at the settings block"
#endif
#if SUSAMUNE_LAUNCHER_MUSIC_PPC_BASE < SUSAMUNE_MEM2_SNAPSHOT_PPC_BASE || \
    SUSAMUNE_LAUNCHER_MUSIC_PPC_BASE + SUSAMUNE_LAUNCHER_MUSIC_SIZE > \
        SUSAMUNE_MEM2_SNAPSHOT_PPC_BASE + SUSAMUNE_MEM2_SNAPSHOT_SIZE || \
    (SUSAMUNE_LAUNCHER_MUSIC_PPC_BASE & 31u) != 0 || \
    (SUSAMUNE_LAUNCHER_MUSIC_SIZE & 31u) != 0
#error "Launcher music overlay must fit and align inside the snapshot window"
#endif
#if SUSAMUNE_LAUNCHER_GCN_IPL_PPC_BASE < NIN_MEM2_DIMM_PPC_BASE || \
    SUSAMUNE_LAUNCHER_GCN_IPL_PPC_BASE + SUSAMUNE_LAUNCHER_GCN_IPL_SIZE > \
        NIN_MEM2_DIMM_PPC_BASE + NIN_MEM2_DIMM_SIZE || \
    (SUSAMUNE_LAUNCHER_GCN_IPL_PPC_BASE & 31u) != 0 || \
    (SUSAMUNE_LAUNCHER_GCN_IPL_SIZE & 31u) != 0
#error "Launcher GameCube IPL overlay must fit and align inside DIMM memory"
#endif
#if SUSAMUNE_MEM2_CFG_PHYS_BASE + SUSAMUNE_MEM2_CFG_SIZE != NIN_MEM2_KERNEL_PHYS_BASE
#error "MEM2 settings block must end at the Nintendont kernel"
#endif
#if SUSAMUNE_MEM2_PB_LIVE_PPC_BASE + SUSAMUNE_MEM2_PB_LIVE_SIZE != NIN_MEM2_KERNEL_PPC_BASE
#error "MEM2 live PB mirror must end at the Nintendont kernel"
#endif
#if SUSAMUNE_DOLPHIN_SNAPSHOT_PPC_BASE + SUSAMUNE_MEM2_SNAPSHOT_SIZE != SUSAMUNE_DOLPHIN_RUNTIME_PPC_BASE
#error "Dolphin runtime state must follow the snapshot window"
#endif
#if SUSAMUNE_DOLPHIN_RUNTIME_PPC_BASE + SUSAMUNE_DOLPHIN_RUNTIME_SIZE != 0x71000000u
#error "Dolphin runtime state must stay inside its 16 MiB aperture"
#endif
#if SUSAMUNE_DOLPHIN_GHOST_RECORD_PPC_BASE != 0x71000000u || SUSAMUNE_DOLPHIN_GHOST_RECORD_PPC_BASE + SUSAMUNE_GHOST_SLOT_SIZE != SUSAMUNE_DOLPHIN_GHOST_PLAY_PPC_BASE || SUSAMUNE_DOLPHIN_GHOST_PLAY_PPC_BASE + SUSAMUNE_GHOST_SLOT_SIZE != SUSAMUNE_DOLPHIN_GHOST_TRANSFER_PPC_BASE
#error "Dolphin ghost slots must be adjacent"
#endif
#if SUSAMUNE_DOLPHIN_PERSIST_PPC_BASE < SUSAMUNE_DOLPHIN_RUNTIME_PPC_BASE || SUSAMUNE_DOLPHIN_PERSIST_PPC_BASE + SUSAMUNE_DOLPHIN_PERSIST_SIZE > SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE
#error "Dolphin persistence state overlaps another MEM2 window"
#endif
#if SUSAMUNE_DOLPHIN_PERSIST_PPC_BASE + SUSAMUNE_DOLPHIN_PERSIST_SIZE > SUSAMUNE_DOLPHIN_RECORDS_PPC_BASE || SUSAMUNE_DOLPHIN_RECORDS_PPC_BASE + SUSAMUNE_RECORDS_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_METADATA_PPC_BASE || SUSAMUNE_DOLPHIN_METADATA_PPC_BASE + SUSAMUNE_METADATA_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_CREATION_PPC_BASE || SUSAMUNE_DOLPHIN_CREATION_PPC_BASE + SUSAMUNE_CREATION_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_REGIONAL_PPC_BASE || SUSAMUNE_DOLPHIN_REGIONAL_PPC_BASE + SUSAMUNE_REGIONAL_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_MENU_PPC_BASE || SUSAMUNE_DOLPHIN_MENU_PPC_BASE + SUSAMUNE_MENU_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_CONFIG_PPC_BASE || SUSAMUNE_DOLPHIN_CONFIG_PPC_BASE + SUSAMUNE_CONFIG_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_FEATURE_PPC_BASE || SUSAMUNE_DOLPHIN_FEATURE_PPC_BASE + SUSAMUNE_FEATURE_RUNTIME_SIZE > SUSAMUNE_DOLPHIN_ILING_PPC_BASE || SUSAMUNE_DOLPHIN_ILING_PPC_BASE + SUSAMUNE_ILING_RUNTIME_SIZE != SUSAMUNE_DOLPHIN_STAGE_LOADER_PPC_BASE || SUSAMUNE_DOLPHIN_STAGE_LOADER_PPC_BASE + SUSAMUNE_STAGE_LOADER_RUNTIME_SIZE != SUSAMUNE_DOLPHIN_CRASH_PPC_BASE || SUSAMUNE_DOLPHIN_CRASH_PPC_BASE + SUSAMUNE_MEM2_CRASH_SIZE != SUSAMUNE_DOLPHIN_STAGE_LOADER_QUEUE_PPC_BASE || SUSAMUNE_DOLPHIN_STAGE_LOADER_QUEUE_PPC_BASE + SUSAMUNE_STAGE_LOADER_QUEUE_SIZE > SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE
#error "Dolphin Susamune runtime windows overlap"
#endif
#if SUSAMUNE_CONSOLE_RECORDS_PPC_BASE + SUSAMUNE_RECORDS_RUNTIME_SIZE > SUSAMUNE_CONSOLE_METADATA_PPC_BASE || SUSAMUNE_CONSOLE_METADATA_PPC_BASE + SUSAMUNE_METADATA_RUNTIME_SIZE > SUSAMUNE_CONSOLE_CREATION_PPC_BASE || SUSAMUNE_CONSOLE_CREATION_PPC_BASE + SUSAMUNE_CREATION_RUNTIME_SIZE > SUSAMUNE_CONSOLE_REGIONAL_PPC_BASE || SUSAMUNE_CONSOLE_REGIONAL_PPC_BASE + SUSAMUNE_REGIONAL_RUNTIME_SIZE > SUSAMUNE_CONSOLE_MENU_PPC_BASE || SUSAMUNE_CONSOLE_MENU_PPC_BASE + SUSAMUNE_MENU_RUNTIME_SIZE > SUSAMUNE_CONSOLE_CONFIG_PPC_BASE || SUSAMUNE_CONSOLE_CONFIG_PPC_BASE + SUSAMUNE_CONFIG_RUNTIME_SIZE > SUSAMUNE_CONSOLE_FEATURE_PPC_BASE || SUSAMUNE_CONSOLE_FEATURE_PPC_BASE + SUSAMUNE_FEATURE_RUNTIME_SIZE > SUSAMUNE_CONSOLE_ILING_PPC_BASE || SUSAMUNE_CONSOLE_ILING_PPC_BASE + SUSAMUNE_ILING_RUNTIME_SIZE != SUSAMUNE_CONSOLE_STAGE_LOADER_PPC_BASE || SUSAMUNE_CONSOLE_STAGE_LOADER_PPC_BASE + SUSAMUNE_STAGE_LOADER_RUNTIME_SIZE != SUSAMUNE_CONSOLE_CRASH_PPC_BASE || SUSAMUNE_CONSOLE_CRASH_PPC_BASE + SUSAMUNE_MEM2_CRASH_SIZE != SUSAMUNE_CONSOLE_STAGE_LOADER_QUEUE_PPC_BASE || SUSAMUNE_CONSOLE_STAGE_LOADER_QUEUE_PPC_BASE + SUSAMUNE_STAGE_LOADER_QUEUE_SIZE > SUSAMUNE_MEM2_PB_LIVE_PPC_BASE
#error "console Susamune runtime windows overlap"
#endif
#if SUSAMUNE_DOLPHIN_MENU_TEXT_PPC_BASE + SUSAMUNE_MENU_TEXT_SIZE > SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE || SUSAMUNE_CONSOLE_MENU_TEXT_PPC_BASE + SUSAMUNE_MENU_TEXT_SIZE > SUSAMUNE_MEM2_PB_LIVE_PPC_BASE
#error "Stage targets and menu text exceed their runtime gap"
#endif
#if SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE + SUSAMUNE_DOLPHIN_PB_LIVE_SIZE > SUSAMUNE_DOLPHIN_RUNTIME_PPC_BASE + SUSAMUNE_DOLPHIN_RUNTIME_SIZE
#error "Dolphin live PB mirror exceeds its MEM2 window"
#endif
#if (SUSAMUNE_DOLPHIN_PERSIST_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_RECORDS_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_METADATA_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_CREATION_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_REGIONAL_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_MENU_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_CONFIG_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_FEATURE_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_ILING_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_STAGE_LOADER_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_CRASH_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_STAGE_LOADER_QUEUE_PPC_BASE & 31u) != 0 || (SUSAMUNE_DOLPHIN_PB_LIVE_PPC_BASE & 31u) != 0
#error "Dolphin runtime-state windows must be cache-line aligned"
#endif
#if (SUSAMUNE_CONSOLE_RECORDS_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_METADATA_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_CREATION_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_REGIONAL_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_MENU_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_CONFIG_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_FEATURE_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_ILING_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_STAGE_LOADER_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_CRASH_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_STAGE_LOADER_QUEUE_PPC_BASE & 31u) != 0
#error "console runtime-state windows must be cache-line aligned"
#endif
#if (SUSAMUNE_DOLPHIN_STAGE_TARGETS_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_STAGE_TARGETS_PPC_BASE & 31u) != 0
#error "Stage target persistence must be cache-line aligned"
#endif
#if (SUSAMUNE_DOLPHIN_MENU_TEXT_PPC_BASE & 31u) != 0 || (SUSAMUNE_CONSOLE_MENU_TEXT_PPC_BASE & 31u) != 0
#error "Menu text scratch must be cache-line aligned"
#endif

// Physical-to-PPC cached alias checks.
#if NIN_MEM2_DISC_CACHE_PHYS_BASE + 0x80000000u != NIN_MEM2_DISC_CACHE_PPC_BASE
#error "Invalid disc-cache PPC alias"
#endif
#if NIN_MEM2_SEGABOOT_PHYS_BASE + 0x80000000u != NIN_MEM2_SEGABOOT_PPC_BASE
#error "Invalid SegaBoot PPC alias"
#endif
#if NIN_MEM2_DIMM_PHYS_BASE + 0x80000000u != NIN_MEM2_DIMM_PPC_BASE
#error "Invalid DIMM PPC alias"
#endif
#if NIN_MEM2_DI_SCRATCH_PHYS_BASE + 0x80000000u != NIN_MEM2_DI_SCRATCH_PPC_BASE
#error "Invalid DI-scratch PPC alias"
#endif
#if NIN_MEM2_LOADER_DISC_PHYS_BASE + 0x80000000u != NIN_MEM2_LOADER_DISC_PPC_BASE
#error "Invalid loader-disc PPC alias"
#endif
#if SUSAMUNE_CONSOLE_GHOST_RECORD_PHYS_BASE + 0x80000000u != SUSAMUNE_CONSOLE_GHOST_RECORD_PPC_BASE || SUSAMUNE_CONSOLE_GHOST_PLAY_PHYS_BASE + 0x80000000u != SUSAMUNE_CONSOLE_GHOST_PLAY_PPC_BASE || SUSAMUNE_CONSOLE_GHOST_TRANSFER_PHYS_BASE + 0x80000000u != SUSAMUNE_CONSOLE_GHOST_TRANSFER_PPC_BASE
#error "Invalid console ghost-slot PPC alias"
#endif
#if NIN_MEM2_FILE_PATCH_PHYS_BASE + 0x80000000u != NIN_MEM2_FILE_PATCH_PPC_BASE
#error "Invalid file-patch PPC alias"
#endif
#if SUSAMUNE_MEM2_SNAPSHOT_PHYS_BASE + 0x80000000u != SUSAMUNE_MEM2_SNAPSHOT_PPC_BASE
#error "Invalid snapshot PPC alias"
#endif
#if SUSAMUNE_MEM2_MODBIN_PHYS_BASE + 0x80000000u != SUSAMUNE_MEM2_MODBIN_PPC_BASE
#error "Invalid mod-blob PPC alias"
#endif
#if SUSAMUNE_MEM2_CFG_PHYS_BASE + 0x80000000u != SUSAMUNE_MEM2_CFG_PPC_BASE
#error "Invalid settings-block PPC alias"
#endif
#if SUSAMUNE_CONSOLE_CRASH_PHYS_BASE + 0x80000000u != SUSAMUNE_CONSOLE_CRASH_PPC_BASE
#error "Invalid crash-mailbox PPC alias"
#endif
#if SUSAMUNE_CONSOLE_STAGE_TARGETS_PHYS_BASE + 0x80000000u != SUSAMUNE_CONSOLE_STAGE_TARGETS_PPC_BASE
#error "Invalid stage-target PPC alias"
#endif
#if NIN_MEM2_KERNEL_PHYS_BASE + 0x80000000u != NIN_MEM2_KERNEL_PPC_BASE
#error "Invalid kernel PPC alias"
#endif

#if SUSAMUNE_GHOST_INPUT_RECORD_PPC_BASE + SUSAMUNE_GHOST_INPUT_BANK_SIZE != SUSAMUNE_GHOST_INPUT_PLAY_PPC_BASE || SUSAMUNE_GHOST_INPUT_PLAY_PPC_BASE + SUSAMUNE_GHOST_INPUT_BANK_SIZE != SUSAMUNE_GHOST_FILE_TRANSFER_PPC_BASE || SUSAMUNE_GHOST_FILE_TRANSFER_PPC_BASE + SUSAMUNE_GHOST_FILE_TRANSFER_SIZE != SUSAMUNE_STATE_STORAGE_PPC_BASE || SUSAMUNE_STATE_STORAGE_PPC_BASE + SUSAMUNE_STATE_STORAGE_SIZE != SUSAMUNE_MEM2_MODBIN_PPC_BASE
#error "Ghost teaching buffers must tile the reclaimed patch tail"
#endif
#if SUSAMUNE_STATE_POOL_EXTRA_PHYS_BASE + 0x80000000u != SUSAMUNE_STATE_POOL_EXTRA_PPC_BASE
#error Invalid additional state-pool alias
#endif
#if SUSAMUNE_DOLPHIN_STATE_POOL_EXTRA_PPC_BASE < SUSAMUNE_DOLPHIN_STATE_STAGING_PPC_BASE + SUSAMUNE_STATE_STAGING_SIZE + 32u || SUSAMUNE_DOLPHIN_STATE_POOL_EXTRA_PPC_BASE + SUSAMUNE_STATE_POOL_EXTRA_SIZE > 0x72000000u
#error Additional Dolphin state bank overlaps live storage
#endif
#if SUSAMUNE_STATE_STORAGE_PHYS_BASE + 0x80000000u != SUSAMUNE_STATE_STORAGE_PPC_BASE || (SUSAMUNE_STATE_STORAGE_PPC_BASE & 31u) || (SUSAMUNE_DOLPHIN_STATE_STORAGE_PPC_BASE & 31u)
#error "Invalid state mailbox alias or alignment"
#endif
#if SUSAMUNE_GHOST_INPUT_RECORD_PHYS_BASE + 0x80000000u != SUSAMUNE_GHOST_INPUT_RECORD_PPC_BASE || SUSAMUNE_GHOST_INPUT_PLAY_PHYS_BASE + 0x80000000u != SUSAMUNE_GHOST_INPUT_PLAY_PPC_BASE || SUSAMUNE_GHOST_FILE_TRANSFER_PHYS_BASE + 0x80000000u != SUSAMUNE_GHOST_FILE_TRANSFER_PPC_BASE
#error "Invalid ghost teaching PPC alias"
#endif
#if SUSAMUNE_MEM2_MENU_TEXT_PPC_BASE + SUSAMUNE_MENU_TEXT_SIZE > SUSAMUNE_MEM2_BINDS_RUNTIME_PPC_BASE || SUSAMUNE_MEM2_BINDS_RUNTIME_PPC_BASE + SUSAMUNE_FOXTROT_BINDS_SIZE != SUSAMUNE_MEM2_SETTINGS_RUNTIME_PPC_BASE || SUSAMUNE_MEM2_SETTINGS_RUNTIME_PPC_BASE + SUSAMUNE_FOXTROT_SETTINGS_SIZE > SUSAMUNE_MEM2_MENU_RUNTIME_PPC_BASE || (SUSAMUNE_MEM2_MENU_RUNTIME_PPC_BASE & 0xFFFFu) + SUSAMUNE_FOXTROT_MENU_RUNTIME_SIZE > 0x8280u
#error "FOXTROT live config and menu exceed their reserved gap"
#endif
#if SUSAMUNE_SPLIT_STATS_MAILBOX_OFFSET + SUSAMUNE_SPLIT_STATS_MAILBOX_SIZE > SUSAMUNE_GHOST_SECONDARY_HEAP_OFFSET || (SUSAMUNE_SPLIT_STATS_MAILBOX_OFFSET & 31u) || (SUSAMUNE_SPLIT_STATS_MAILBOX_SIZE & 31u)
#error "Split-statistics mailbox overlaps the secondary model heap or is unaligned"
#endif
#endif // SUSAMUNE_MEM2_MAP_H
